### ISSUE TITLE
traceroute and ipset should be mentioned as dependencies

### ISSUE THREAD

**Issue by SanskritFritz** [firehol/firehol#119]
in the wiki https://github.com/firehol/firehol/wiki/Dependencies
traceroute and ipset are not mentioned. However configure fails without them.

**Comment by philwhineray** [comment]
Updated, thanks.

In general reading the `configure.ac` file will likely always be a more reliable source of information, however.

**Comment by ktsaou** [comment]
I added a link to the configure.ac file in the wiki page.

**Comment by SanskritFritz** [comment]
Thanks.
