### ISSUE TITLE
git head build fails on man/man5/vnetbuild-bridgedev.5

### ISSUE THREAD

**Issue by SanskritFritz** [firehol/firehol#120]
Here is the output:
```
Making all in vnetbuild
make[2]: Entering directory '/home/frank/Builds/aur4/SanskritFritz/firehol-git/src/firehol/doc/vnetbuild'
/usr/bin/mkdir -p man/man1
/usr/bin/mkdir -p man/man5
make[2]: *** No rule to make target 'man/man5/vnetbuild-bridgedev.5', needed by 'all-am'.  Stop.
make[2]: *** Waiting for unfinished jobs....
/usr/bin/sed -e '/^%/s/DATE/26 Jan 2016/' -e '/^%/s/VERSION/3.0.2_master/' vnetbuild.1.md > tmp-manproc
/usr/bin/sed -e '/^%/s/DATE/26 Jan 2016/' -e '/^%/s/VERSION/3.0.2_master/' vnetbuild-conf.5.md > tmp-manproc
/usr/bin/sed -e 's/: .*#/: #/' ../../doc/links-internal-vnetbuild ../../doc/links-keywords-vnetbuild ../../doc/links-website-vnetbuild > tmp-anchor-links
/usr/bin/pandoc -f markdown -t man -s -o man/man1/vnetbuild.1 tmp-manproc tmp-anchor-links
/usr/bin/sed -e 's/: .*#/: #/' ../../doc/links-internal-vnetbuild ../../doc/links-keywords-vnetbuild ../../doc/links-website-vnetbuild > tmp-anchor-links
/usr/bin/pandoc -f markdown -t man -s -o man/man5/vnetbuild-conf.5 tmp-manproc tmp-anchor-links
../../doc/tools/pandoc-post 1.16.0.2 man man/man1/vnetbuild.1
../../doc/tools/pandoc-post 1.16.0.2 man man/man5/vnetbuild-conf.5
../../doc/tools/man-synos vnetbuild.1.md man/man1/vnetbuild.1 man/
../../doc/tools/man-synos vnetbuild-conf.5.md man/man5/vnetbuild-conf.5 man/
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild.conf.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-host.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-switch.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-dev.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-bridgedev.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-route.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-exec.5
Created man5/vnetbuild-conf.5 -> man/man5/vnetbuild-pre_up.5
make[2]: Leaving directory '/home/frank/Builds/aur4/SanskritFritz/firehol-git/src/firehol/doc/vnetbuild'
Makefile:490: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/frank/Builds/aur4/SanskritFritz/firehol-git/src/firehol/doc'
Makefile:436: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by philwhineray** [comment]
Did you build from a clean directory? It looks like
--enable-maintainer-mode was not passed to configure, but recent versions
should prevent this.

Maybe you need to redo ./autogen.sh?

**Comment by SanskritFritz** [comment]
I deleted the build dir, now it fails like this:
```make[2]: *** No rule to make target 'man/man5/fireqos-ack.5', needed by 'all-am'.  Stop.```

**Comment by philwhineray** [comment]
Try running:

./packaging/git-build

**Comment by SanskritFritz** [comment]
I got the same error.

**Comment by philwhineray** [comment]
Versions don't really help if you are using the git tree, especially for peripheral files like docs. If you think you are on git HEAD (which works for me), check that:

~~~~
git rev-parse HEAD
~~~~

outputs the current HEAD (`6c426bd9b2127ea2307e2e88709947bc0aac310a`)

and that

~~~~
git status --short
~~~~

outputs nothing (i.e. there are no changes).

If this all checks out, please include the complete output of the

~~~~
./packaging/git-build
~~~~

**Comment by SanskritFritz** [comment]
Ah, this way it looks good. So there is a problem with the build script I'm using.
https://gist.github.com/anonymous/979f4bea5218ff4ee984

**Comment by philwhineray** [comment]
Thanks fot the info but I'm a bit confused. Are you still asking for help
or are you satisfied the repo is OK?

**Comment by SanskritFritz** [comment]
I will reopen this if I need more help, thanks!

**Comment by SanskritFritz** [comment]
Would you be so kind and check this output for me? I simply embedded ./packaging/git-build into the build script and got the error. In theory it should do the same as you described. But it fails this way. Maybe you can spot the problem?
https://gist.github.com/anonymous/d4fe7a7dca4c7cdd68a0

**Comment by philwhineray** [comment]
I think maybe your script somehow sets 'make' to do multiple jobs simultaneously? Does it set '-j' in MAKEFLAGS for example? Some of the docs are created as others are processed and it looks like this is happening out of order.

**Comment by SanskritFritz** [comment]
Woa, that was the solution, thank you! Indeed there is a 
MAKEFLAGS="-j2"
in the config.
