### ISSUE TITLE
Redirect outgoing traffic to specific interfaces

### ISSUE THREAD

**Issue by raedah** [firehol/firehol#129]
My goal is to direct specific outgoing traffic types out through hotspot, and let the remaining outgoing traffic go through the tether. Is this possible, or does this depend on my default gateway?

sudo fireqos status hotspot-out , shows no traffic
sudo fireqos status tether-out , shows traffic

$ cat /etc/firehol/fireqos.conf
interface tun tether-in input rate 12000kbit
interface tun tether-out output rate 800kbit

interface wifi hotspot-in input rate 12000kbit
interface wifi hotspot-out output rate 800kbit

$ cat /etc/firehol/firehol.conf
interface wifi hotspot
    policy accept
    client http accept
    client https accept
    client ssh accept
    client ftp accept

interface tun tether
    policy accept
    client all accept

**Comment by ktsaou** [comment]
So, you have 2 gateways:

1. hostpost
2. tether

Do you want to load-balance these gateways, or you want specific traffic to go through hotspot and all the other though tether?

If it is specific traffic, which one?

If it is specific traffic, in general, this is what you are going to need:

1. When you need 2 default gateways, you also need 2 routing tables. FireHOL has a tool for this: `link-balancer`: https://github.com/firehol/firehol/wiki/Link-Balancer

 This tool can copy the routing table you already have to another one, and then change the default gateway on the second. It can also use various conditions to make the traffic in question use the second routing table.

2. Somehow we have to select the traffic. If it is something simple (like the destination IP), it can be done directly with an `ip rule` command. It if is more complicated, you will have to mark the traffic in firehol.conf and then tell link-balancer you want the marked traffic to use the 2nd routing table.

3. When you have 2 default gateways, another problem arises: If a host behind one of them is willing to talk to you, then you should respond back via the same gateway, or it will not work. This is again a job of firehol and link-balancer.

In general, you will not need fireqos for this task.

So, decide which traffic you need to route via the second default gateway and I'll point you to the proper skeleton for your firehol.conf and link-balancer.conf.

**Comment by raedah** [comment]
I would like all Tor traffic to go out through 'tether', and everything else to go out through 'hotspot'.

**Comment by ktsaou** [comment]
Well, tor is not something that can be matched. (At least I don't know how).

Regarding `rt_tables` both are the same `NUMBER NAME` (wrong wording I guess).

Regarding the rules, this is the tricky part (and the reason why tor cannot be matched). You can re-route traffic based on source, destination ports/ips and possibly marks (but marks are again assigned with the same attributes and possibly a few more, like connection tracker states). There is no TOR match in iptables...

**Comment by raedah** [comment]
Since there is no TOR match in iptables, maybe i can just try to catch as much as the traffic to the other interface as I can. So send http, https, ftp and ssh to 'hotspot', and then let everything else (including Tor) go to 'tether'.

Another possibility I read about is to "use -m owner and --uid, and also CONNMARK, and tc(8) so packets created by processes running as a specific user get a specific mark and thus are routed via a specific gateway". For this, it looks like I would need to execute app going to the other interface from a separate user session.

If you can point me to the proper skeleton for your firehol.conf and link-balancer.conf for either of these configs, that would be great. Firehol looks like a high quality project.
