### ISSUE TITLE
Can't disable logging dropped packets

### ISSUE THREAD

**Issue by drobinsk** [firehol/firehol#142]
It looks like firehol always logs dropped packets. Is it possible to disable this in firehol-defaults.conf?
It would be really useful when running on embedded systems.

`FIREHOL_LOG_DROP_INVALID=0`

doesn't work for me.

**Comment by philwhineray** [comment]
A dropped packet is not necessarily an invalid packet.

By default, FireHOL will log any packet that did not match a rule and then
drop it.

If you want to avoid logging anything, just create a final anystateless
rule (after all your accepts) and deny it.

Or, if you have a particular noisy port, create a deny or reject rule just
for that, then you can still see more unusual logs.

**Comment by drobinsk** [comment]
Thank you, it helped however switching off logs at configuration level still could be useful feature.

**Comment by daenney** [comment]
Set: `FIREHOL_LOG_PREFIX="firehol: " in `/etc/firehol/firehol.conf` and then (for rsyslog) add `/etc/rsyslog.d/01-firehol.conf`:
```
:msg, contains, "firehol:" /dev/null
& stop
```

Alternatively you can send it to a different file like `-/var/log/firehol.log` but don't forget to add a log rotate for it!

**Comment by philwhineray** [comment]
I don't really agree with the need for an explicit option to switch off logging, although I will accept a pull request if someone writes the required code.

I have compiled a FAQ which contains all of the current options. For your purposes, simply switching to NFLOG and not bothering to install ulogd will probably work.

**Comment by philwhineray** [comment]
Link to FAQ:

https://firehol.org/faq/#firehol-logging

**Comment by nyuszika7h** [comment]
systemd-journald doesn't seem to have a way to ignore specific log lines. Even if I add a filter in rsyslog, the journal is still spammed with firehol messages.

Netiher `FIREHOL_LOG_MODE="NFLOG"` nor `FIREHOL_LOG_MODE="ULOG"` had any effect.
