### ISSUE TITLE
Possible incorrect instructions on matching LAN traffic in wiki?

### ISSUE THREAD

**Issue by level323** [firehol/firehol#149]
Hi there,

As this is my first contribution to this project I must begin by expressing my great thanks for the awesome Firehol/Fireqos/Netdata suite! It's made my life a whole lot easier!

As I want to enable classification based on the LAN client IPs and ports, I had to (as suggested in the docs/wiki) switch the fireqos configuration to classify traffic on the LAN port (rather than the WAN port). 

The Wiki gives some guidance on how to do this here: https://github.com/firehol/firehol/wiki/FireQOS#fireqos-configuration

Specifically the following sample configuration, which shows how to leave non-WAN traffic running at full gigabit rates and only limiting traffic destined for the WAN

```shell
interface eth0 lan output rate 1Gbit ethernet

   class lan
      match dst 192.168.0.0/24 # <<< LAN traffic

   class group adsl rate 10Mbit ceil 10Mbit adsl remote pppoe-llc # <<< hardware emulation
      match all # <<< send all other traffic to this group

      class voip # <<< class in the adsl group
         match udp port 5060

      class web # <<< class in the adsl group
         match tcp port 80,443

    class group end
```

But it seems to me that for `class lan` the `match dst` should actually be `match src`, no? The interface stanza covers traffic egress from the LAN port. Therefore traffic leaving this port that was *not* coming from the WAN would have to be matched on the *source* IP being a LAN address, not the destination IP.

In other words, I think the above sample config should be re-written as follows:

```shell
interface eth0 lan output rate 1Gbit ethernet

   class lan
      match src 192.168.0.0/24 # <<< LAN traffic

   class group adsl rate 10Mbit ceil 10Mbit adsl remote pppoe-llc # <<< hardware emulation
      match all # <<< send all other traffic to this group

      class voip # <<< class in the adsl group
         match udp port 5060

      class web # <<< class in the adsl group
         match tcp port 80,443

    class group end
```

Indeed, what I found when adapting the original sample config to my setup (that is using `match dst` for the `lan` class) was that all traffic originating from the WAN (in fact, basically all traffic egress on the LAN port) got matched by the `lan` class, and therefore not shaped according to the `adsl` class group. 

Changiing it to `match src` seemed to make it work as intended.

Is my assessment correct or have a made a serious blunder?

**Comment by ktsaou** [comment]
What `src` and `dst` match depend on the `input` and `output` direction of the interface.

So, for your lan interface, `src` on `input` and `dst` on `output` should be your lan computers.

I suggest to change `match all` to `match dst 8.8.8.8` (this is the google name server) and then just ping 8.8.8.8. Do you see just the pings in netdata or is there any more traffic?

Similarly, you can create a test class the match only the IP of 1 computer. Then ping that computer to verify in netdata it matches as it should.

**Comment by level323** [comment]
> What src and dst match depend on the input and output direction of the interface.

Couldn't agree more.

> So, for your lan interface, src on input and dst on output should be your lan computers.

I disagree, and the tests you asked me to perform only confirm my disagreement.

Instead of using the example from the wiki to illustrate my point I'll paste an excerpt of the relevant part of my `firehol.conf` below. I've used pings to 8.8.4.4 (Google's secondary DNS) as the test because other devices on my lan use the Google's primary DNS regularly.

```
<snip>
interface $DEVICE lan-out output rate 1Gbit balanced minrate 100kbit

    class lan
        match src 10.0.1.0/24     # All traffic destined for a LAN client

    class test
        match src 8.8.4.4  # Test

    class group adsl rate $OUTPUT_SPEED ceil $OUTPUT_SPEED balanced $LINKTYPE
        match all

        class voip              prio 1  commit 1000kbit pfifo
        class interactive       prio 2  commit 1000kbit

<snip>
```

The above *correctly* classifies ping responses from 8.8.4.4 to the `test` class.

If I change `match src 10.0.1.0/24` to `match dst 10.0.1.0/24` (what you and the wiki say it should be) then those ping responses get classed in the `lan` class, which is not what is desired. Furthermore, all the traffic from the WAN now gets classified in the `lan` class, which is clearly undesirable.

Not only does using `march src` on `output` interfaces work as it should, but it also makes sense to me when I mentally step through whats going on here. The above interface is an `output` interface, so it will be attempting to classify traffic being routed from the WAN (ingress on the WAN interface) to computers on the LAN (egress on the LAN interface). More correctly, it will be classifying *all* traffic leaving the LAN interface but the main role of this machine is a WAN router/nat/gateway/firewall so the bulk of the traffic leaving the LAN port will indeed originating from the WAN. Therefore, all traffic travelling along that route will have a destination address that is on the LAN subnet (in my case 10.0.1.0/24). Therefore using a `match dst` on this `output` `interface` definition should (and does) classify basically every packet leaving the LAN interface as the `lan` class, including traffic originating from the WAN (which is the bulk of the traffic egressing from the LAN interface anyway).

Similarly (but not shown in the snippet above), I must use a `match dst` on the `input` interface stanza for my LAN interface for proper classification of traffic originating from local LAN computers destined for the WAN. If I use `match src` (as you suggest I should) then all of this traffic destined for the LAN also gets classified as being of the `lan` class.

Try it for yourself. I'm pretty confident now that you can confirm this.

I'm wondering if you've been staring at this stuff so long you've overlooked the obvious? I do that all the time on projects I've been involved with for a long time ;-)

**Comment by ktsaou** [comment]
You are right. I think however, that even you proposal is not good enough.

The problem is that when lan computer A wants to talk to the internet, then the **gateway** will see:

## Request going from A to INTERNET:

1. input: src A -> dst INTERNET (lan to gateway)
2. output: src A -> dst INTERNET (gateway to internet)

## Response coming back from INTERNET to A:

1. input: src INTERNET -> dst A (internet to gateway)
2. output: src INTERNET -> dst A (gateway to lan)

As you can see, there is no way to do it right. The first match for A will get the traffic. So either `gateway to internet` or `gateway to lan` will be wrong.

The only way I can think of is to SNAT the packets towards the router, so that the packets going to the internet will always have source IP the IP of the gateway, or mark the packets going to the internet using iptables.

**Comment by ktsaou** [comment]
I still don't see though why this does not match the traffic properly:

```
lan="192.168.0.0/24"

interface eth0 lan output rate 1Gbit ethernet

   class lan
      match dst "${lan}"

   class group adsl rate 10Mbit ceil 10Mbit adsl remote pppoe-llc # <<< hardware emulation
      match src "${lan}"

      class voip # <<< class in the adsl group
         match udp port 5060

      class web # <<< class in the adsl group
         match tcp port 80,443

    class group end
```

**Comment by ktsaou** [comment]
I edited my responses, so check them on github

**Comment by level323** [comment]
My short response is that after quite a bit of testing my `fireqos.conf` on the gateway in question is QoSing very well now and correctly classifying packets in both directions (by classifying traffic in and out of the LAN interface), but in order to do so the only conceptual change I made to the advice in wiki is to change `match dst`` for the `lan` output class to `match src` and vice versa for the `lan` input class. Nothing appears (as far as I can see thus far) to be being missed or mis-classified.

My longer response will have to wait as I have some work deadlines. Hopefully I can respond in the next 48 hrs.

**Comment by level323** [comment]
OK, so I'll have a go at describing what I think the gateway will see.

Traffic described below is expressed from the point of view of **fireqos monitoring the LAN interface on the gateway machine** (unless explicitly stated otherwise). That is, I'm ignoring what happens on the WAN interface both because fireqos (in my case and in the wiki docs previously referred to) is not classifying traffic on this interface and it is not relevant and just confuses the analysis.

I'm going to attempt to step through this logically in the hope that we can agree or else discern the flaw(s) in my/your thinking.

Taking this approach I can group the traffic into four distinct groups that suit our purpose:

## INCOMING LOCAL-ONLY TRAFFIC: Traffic from machine A on the LAN to another machine B on the same LAN that (for whatever reason) transits via the gateway:

Note: although handling this type of traffic is not the main purpose of the gateway machine we ought to consider it so we can  understand what's going on and (as is the whole point of this discussion) to discern the correct rules so that local traffic doesn't get caught up in the QoS system for traffic to/from the internet and thereby slowed unnecessarily.

In this case the LAN interface on the gateway receives **incoming** IP packets with a `src` IP of A and a `dst` IP of B

### My conclusion on the proper way to classify this traffic:

1. We are dealing with **incoming** packets on the LAN interface and therefore fireqos rules to classify these packets must be placed inside an `interface $LAN_DEVICE lan-in input ...` stanza  (or similar, as long as it's an `input`).
2. In isolation we could classify these packets as members of the `lan` class with a `match` rule on the either (or even both of) the `src` or `dst` IP are on the LAN subnet. However, for the sake of providing an easy way to categorise incoming traffic that is bound for the INTERNET (via a `match all` rule as discussed further below) I will elect to classify these packets via a `match dst $LAN_SUBNET` rule. Expressed another way, although a `match src $LAN_SUBNET` would indeed match this traffic, it would also undesirably match traffic that is destined for the INTERNET so we should *not* us a `match src` rule for this task.

## OUTGOING LOCAL-ONLY TRAFFIC: Response from machine B on the LAN back to machine A on the same LAN that (for whatever reason) transits via the gateway:

Note: again, handling this kind of traffic is not the main function of the gateway but by differentiating it we can avoid LAN-only traffic getting QoS'd as though it was traversing the (much slower) internet link. 

In this case the LAN interface on the gateway **outputs** IP packets with a `src` IP of B and a `dst` IP of A

### My conclusion on the proper way to classify this traffic:

1. We are dealing with **outgoing** packets on the LAN interface and therefore fireqos rules to classify these packets must be placed inside an `interface $LAN_DEVICE lan-out output ...` stanza (or similar, as long as it's an `output`).
2. In isolation we could classify these packets as members of the `lan` class with a `match` rule on the either (or even both of) the `src` or `dst` IP are on the LAN subnet. However, for the sake of providing an easy way to categorise outgoing traffic that originated from the INTERNET (via a `match all` rule as discussed further below) I will elect to classify these packets via a `match src $LAN_SUBNET` rule. Expressed another way, although a `match dst $LAN_SUBNET` would indeed match this traffic, it would also undesirably match traffic that came from the INTERNET and was returning to A so we should *not* us a `match dst` rule for this task.

## INCOMING INTERNET TRAFFIC: Request going from computer A on the LAN to some machine on INTERNET:

In this case the LAN interface on the gateway receives **incoming** IP packets with a `src` IP of A and a `dst` IP of INTERNET_ADDR

### My conclusion on the proper way to classify this traffic:

1. We are dealing with **incoming** packets on the LAN interface and therefore fireqos rules to classify these packets must be placed inside an `interface $LAN_DEVICE lan-in input ...` stanza  (or similar, as long as it's an `input`).
2. If we ensure `lan` class and associated  `match dst $LAN_SUBNET` rule (for INCOMING LOCAL-ONLY TRAFFIC) comes first, then we can classify all other traffic as INTERNET traffic very easily by adding a `match all` rule. We can place this rule inside a `class group` to further sub-classify and selectively QoS different types of INTERNET traffic. 

## OUTGOING INTERNET TRAFFIC: Response coming from some machine on the INTERNET to computer A:

In this case the LAN interface on the gateway is **outputting** IP packets with a `src` IP of INTERNET_ADDR and a `dst` IP of A (thanks to the magic of NAT)

### My conclusion on the proper way to classify this traffic:

1. We are dealing with **outgoing** packets on the LAN interface and therefore fireqos rules to classify these packets must be placed inside an `interface $LAN_DEVICE lan-out output ...` stanza (or similar, as long as it's an `output`).
2. If we ensure `lan` class and associated  `match src $LAN_SUBNET` rule (for OUTGOING LOCAL-ONLY TRAFFIC) comes first, then we can classify all other traffic as INTERNET traffic very easily by adding a `match all` rule. We can place this rule inside a `class group` to further sub-classify and selectively QoS different types of INTERNET traffic. 

The above analysis makes perfect sense to me. It explains why the `match src` and `match dst` for `lan` class traffic in the wiki is incorrect and should be reversed. Furthermore, my gateway machine on which I'm running this fireqos QoS configuration (which is a real working gateway serving a real business LAN) is classifying correctly in both directions as we speak.

**Comment by ktsaou** [comment]
Your first 2 cases are not valid. Computers on the same subnet never talk via a gateway. This is entirely handled by ethernet ARP and the machines talk always directly. The only way for 2 computers on the same physical ethernet segment to talk via a gateway, is to have IPs from different subnets.

Can you explain your setup? Why are you matching ADSL traffic on the LAN?

I assumed that your linux gateway has an IP on 192.168.0.0/24 together with you LAN computers. Then I assumed you have an ADSL router/modem on a **different subnet** on the same LAN switch, and your linux gateway has an IP on this subnet too. So, traffic from lan computers to the internet and vice versa, always goes via the linux gateway.

If the above is right, your analysis is incomplete because your linux gateway uses the same ethernet interface for 2 purposes:

1. lan <-> gateway communication
2. gateway <-> internet communication

Check https://github.com/firehol/firehol/issues/149#issuecomment-253088270 above.

**Comment by level323** [comment]
> Your first 2 cases are not valid. Computers on the same subnet never talk via a gateway. This is entirely handled by ethernet ARP and the machines talk always directly. The only way for 2 computers on the same physical ethernet segment to talk via a gateway, is to have IPs from different subnets.

Yes I'm aware that machines on the same subnet normally talk directly to each other, but there are cases where connections that are truly local only (`src` and `dest` on the same subnet) that would flow in and out of the LAN interface on my linux firehol+fireqos gateway. Those cases include:

1. Traffic to/from the gateway itself and other machines on the LAN. Practical examples include backups of config/data on the gateway to a backup host elsewhere on the same subnet, or file transfers more generally and SSH sessions. As this traffic never hits the WAN link it is ideal for it to get classed into the `lan` class otherwise it will end up getting classified into on of the classes meant for managing the much lower bandwidth of the WAN link.

2. As you mentioned, traffic between this subnet (let's call it subnet X) and another subnet (let's call it subnet Y). In some cases it's desirable to have a separate machine that is capable of routing traffic to a specific subnet (such as subnet Y). This is in fact what I do on my network. `snat` can be used to redirect that traffic from the main linux firehol+fireqos gateway to the appropriate machine that can reach and route to subnet Y. That router can be (and *is* in my case) reached via a local IP on subnet X. Yes, I realise I could use one of many route advertising daemons to individually advertise to all the machines on the LAN subnet X of the route to subnet Y directly, but for various reasons (mostly keeping things simple) I use a single central gateway on subnet X to route all traffic both to the WAN and to other LAN subnets (such as subnet Y). Setting up all my hosts with dynamic route management daemons is a layer of complexity I would very much rather avoid (and thankfully I have no need for port forwarding across gateways/routers, which the single gateway `snat`ing to other subnets makes more difficult to implement). And yes, another approach would be to connect all the various subnets directly to the central gateway router and route it all in one step from there - but this also has various administrative and practical downsides which in my circumstances make it a less desirable approach.

If I didn't configure fireqos to classify packets for the above two cases into a `lan` class then they would get unduly limited by the various QoS classes for the WAN link (and thus slowed down a LOT). 

> Can you explain your setup? 

- My local LAN subnet is 10.0.1.0/24
- I have a linux box at 10.0.1.1 running (amongst other things) firehol+fireqos. It acts as a central gateway/router/firewall between machine on the 10.0.1.0/24 subnet and the internet. It also knows that there are some other machines (that are also on the 10.0.1.0/24) that are capable of routing to other subnets (VPN's and such). This machine will `snat` and route traffic destined for those subnets to the machine that can reach that subnet.
- As alluded to in the previous point, I have a number of machines on the 10.0.1.0/24 subnet that tunnel connections to certain VPNs. The central gateway/router at 10.0.1.1 `snat`s and routes traffic addressed to those subnets to these machines as appropriate.

> Why are you matching ADSL traffic on the LAN?

I am matching ADSL traffic on the LAN interface because the more intuitive approach of classifying ADSL traffic on the ADSL interface has the serious (for me) limitation that traffic cannot be classified according to the true IP address of the endpoint machine on the 10.0.1.0/24 subnet. It cannot be classified in this way because (as you know) the actual 10.0.1.0/24 endpoint address has been masqueraded (and replaced by the public IP of the gateway) by the firehol routing process. I really, *really* need to be able to classify traffic according to the true 10.0.1.0/24 endpoint address and carrying out the classification on the LAN side is a means to achieving this (and mentioned in the wiki).

There is no 192.168.0.0/24 subnet in my system - that was only mentioned because I began this ticket by referencing the example code from the wiki which I believed was in error (which uses that subnet).

**Comment by ktsaou** [comment]
So, the internet router is not on the same subnet as your lan. This was a wrong assumption from me.

So, I guess this is the correct:

```sh
lan="10.0.1.0/24"
interface eth0 lan output rate 1Gbit ethernet

   class lan
      match src "${lan}" dst "${lan}"

   class group adsl rate 10Mbit ceil 10Mbit adsl remote pppoe-llc
      match all

      class voip
         match udp port 5060

      class web
         match tcp port 80,443

    class group end
```

Keep in mind that the way you do this, network traffic between your linux gateway and the internet is not taken into account. When your linux gateways downloads something from the internet (or the lan computers download something through possibly a proxy running on the linux gateway), the adsl link will be overflown.

The best solution to solve this (https://github.com/firehol/firehol/wiki/FireQOS-Use-Scenarios#case-2-all-organizations-share-the-same-internet-ip) is to use SNAT to map different IPs to different port on the public side of your linux gateways. For example, you could have computer A mapped to 20001-20500, computer B to 20501-21000, computer C to 210010-21500, etc. This way you can classify traffic on the internet side based on the lan computer that requested the traffic.

**Comment by level323** [comment]
Uh, I thought I made it clear that my internet router **is** on the same subnet as my lan as per my previous post:

> I have a linux box at 10.0.1.1 running (amongst other things) firehol+fireqos. It acts as a central gateway/router/firewall between machine on the 10.0.1.0/24 subnet and the internet. 

Whilst I agree that your proposed code snippet will work `match src "${lan}" dst "${lan}"`, I contend the `dst "${lan}"` part is redundant because the traffic being shaped in your example is always going to have a `dst` IP of `${lan}` because it is travelling out of the LAN interface (and therefore must be destined for another machine on that LAN subnet). 

> Keep in mind that the way you do this, network traffic between your linux gateway and the internet is not taken into account. When your linux gateway downloads something from the internet (or the lan computers download something through possibly a proxy running on the linux gateway), the adsl link will be overflown.

Understood and thanks for this tip. This had escaped my notice. However, through dumb luck I've set my linux gateway up in such a way that it basically never creates traffic to/from the internet directly (perhaps a dribble every now and then such as from ntpd). I don't run any proxies on the linux gateway. So it effectively only routes traffic from other machines so I can consider this matter a non-issue in my case. 

> The best solution to solve this (https://github.com/firehol/firehol/wiki/FireQOS-Use-Scenarios#case-2-all-organizations-share-the-same-internet-ip) is to use SNAT to map different IPs to different ports on the public side of your linux gateway. For example, you could have computer A mapped to 20001-20500, computer B to 20501-21000, computer C to 210010-21500, etc. This way you can classify traffic on the internet side based on the lan computer that requested the traffic.
 
I agree this would work but I question whether it's the *best* in my case. This requires configuration to be added in **two** places - `firehol.conf` and `fireqos.conf` whereas in the LAN-side QoS approach above `firehol.conf` is left alone. Secondly, I contend that managing SNAT port mappings on an IP-by-IP basis would get quite lengthy and cumbersome if there were many LAN machines that needed to be specifically classed. It would get even more cumbersome if the layout of machines on the LAN changed around more frequently. But I agree that using port SNATing would be equally appealing when there are a few LAN IP's you need to put into specific classes and the LAN machine layout doesn't change much.

Back to the original purpose of me raising this ticket: I contend that the example config in the wiki is currently incorrect and should be changed to the following:

```
interface eth0 lan output rate 1Gbit ethernet

   class lan
      match src 192.168.0.0/24 # <<< LAN traffic

   class group adsl rate 10Mbit ceil 10Mbit adsl remote pppoe-llc # <<< hardware emulation
      match all # <<< send all other traffic to this group

      class voip # <<< class in the adsl group
         match udp port 5060

      class web # <<< class in the adsl group
         match tcp port 80,443

    class group end
```

To be clear as to what my proposed change is: `match dst 192.168.0.0/24` should be changed/corrected to `match src 192.168.0.0/24`.

Alternatively (as I think you mentioned), it could be changed to  `match src 192.168.0.0/24 dst 192.168.0/24` but the `dst` term is strictly redundant.

Do you agree?

**Comment by ktsaou** [comment]
> Do you agree?

Example setup:

### `host A` pings `server`, one request goes out, one reply comes back

```
       server
          |
      internet
          |
      adsl router                    linux gateway
          |                                |
      ----+--------------------------------+------
                                           |
                                        host A
```

`linux gateway` = 10.0.0.1 and 192.168.0.1, default gateway 192.168.0.254
`host A` = 10.0.0.2, default gateway 10.0.0.1
`adsl modem` = 192.168.0.254, default gateway to ISP, static route to 10.0.0.0/24 via 192.168.0.1
`server` = 8.8.8.8

`linux gateway` sees on its **output**:

1. request going from `host A` to the `internet server`: packet with `src 10.0.0.2 dst 8.8.8.8`

  This packet should be classified to the `adsl` class. With your suggestion it will go to the `lan` class.

2. reply going from the `internet server` to `host A`: packet with `src 8.8.8.8 dst 10.0.0.2`

  This packet should be classified to the `lan` class. With your suggestion it will go to the `adsl` class.

---

Your suggestion is not valid even when you SNAT all traffic to non LAN IPs at the `linux gateway` (which of course is nice because it avoids the static route at the `adsl router`).

In this case, with SNAT, `linux gateway` sees on its **output**:

1. request going from `host A` to the `internet server`, SNATed: packet with `src 192.168.0.1 dst 8.8.8.8`

  This packet should be classified to the `adsl` class. Both mine and yours will send it there.

2. reply going from the `internet server` to `host A`: packet with `src 8.8.8.8 dst 10.0.0.2`

  This packet should be classified to the `lan` class. With your suggestion it will go to the `adsl` class.

---

So, no I don't agree.

**Comment by ktsaou** [comment]
Sorry! You are right and I am wrong. You are trying to shape internet inbound traffic, not outbound.
I got it wrong!

**Comment by ktsaou** [comment]
Fixed the wiki.
I am probably too tired :)
netdata has got all my energy...

**Comment by level323** [comment]
LOL! I started to wonder if I was going crazy!

I'm glad we finally came to mutual agreement on this.

I don't doubt for a minute that this whole project is consuming so much energy. It's such an excellent project but also very detailed under the hood. I'm definitely not experienced enough with the fine-grained iptables and tc stuff that you clearly are very skilled with and I really do appreciate that firehol/fireqos save me from having to learn it all. Major kudos and thanks to you! Netdata is also fantastic.

Not meaning to sound like a cheerleader or anything but I also must add how much I like the way you've approached the design of these tools (based around bash). I think that's the right approach and cooperates really well with scripted configurations / configuration management.

**Comment by ktsaou** [comment]
thank you for insisting on this!

I talk with too many people every day, and sometimes fast context switching does not help at all. A little detail missed and I end up like this... Anyway, thank you for your patience...

**Comment by level323** [comment]
Reopening this issue because it seems there is another document containing a similar mistake. 

Please see: https://firehol.org/fireqos-manual/fireqos-class/

See the second example in the EXAMPLES section

**Comment by ktsaou** [comment]
fixed it; I think the site will be automatically updated in awhile...

**Comment by level323** [comment]
Excellent. Closing.
