### ISSUE TITLE
How to combine traffic shaping and VPNs?

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#150]
When using something like OpenVPN, it creates a virtual NIC like `tap0` or `tun0` onto which normal packets flow. It then processes these in userspace and sends them out as encrypted blobs of unidentifiable nature over your `eth0`.

Since I'm traffic shaping on my `eth0`, I have no usable way of classifying this traffic other than by sticking it into a big “openvpn” class. But this does not work well at all, because I might have traffic that should be highly interactive and highly bulk coexisting on the same VPN connection, while also mixing with interactive/bulk traffic that goes out directly over the `eth0` interface. I want interactive traffic grouped together and bulk traffic grouped together, regardless of whether it's going through the VPN or not.

The only realistic solution I can think of would be to employ some sort of “split classification” approach, where I apply the classification (corresponding to `client`/`match` rules in `fireqos.conf`) on the plaintext NIC (`tap0`), but apply the traffic shaping itself together with the rest of my packets on `eth0` (corresponding to the `class` definitions).

Is it possible to (without many headaches) set up such a configuration using FireQOS?

**Comment by ktsaou** [comment]
each device has its own QoS.

So, on your `eth0`, you can only match openvpn as you said and prioritize the whole of it related to other `eth0` traffic or other openvpn tunnels. Then, for each openvpn  you can have a separate fireqos `interface` to do whatever magic you like.

**Comment by haasn** [comment]
@ktsaou That doesn't seem to answer my question, except if the answer is “it's impossible”?

Thinking about this some more I'm also not sure how I'd even work around this, since e.g. any MARKs I make to packets will get dropped by OpenVPN reprocessing them, and multiple real packets might also get merged into a single OpenVPN packet. Plus, on the ingress direction it's totally hopeless.

Does the status quo for traffic shaping have to be “don't use VPNs!” for the rest of eternity? I'm using the VPN mainly to provide myself an IPv6 connection on top of my IPv4 conection, but due to the problems discussed I've already had to make it so that my machine prefers IPv4 over IPv6 wherever possible. (Because it essentially means that all IPv6 traffic is completely ignoring traffic shaping rules)

So I suppose I might just end up having to remove IPv6 tunnelling altogether, since it seems to fundamentally contradict QoS. Sad but necessary.

**Comment by ktsaou** [comment]
I don't get it: VPN traffic is encypted. You cannot examine the inners of a VPN from outside the VPN. If you could, this would not be VPN (Virtual Private Network) but a VN (Virtual Network - not private at all).

So, probably I have not understood the question. Could you please explain a bit more what you are trying to do, which problem you are trying to solve?

**Comment by haasn** [comment]
> I don't get it: VPN traffic is encypted. You cannot examine the inners of a VPN from outside the VPN.

But my PC is the VPN endpoint, so in principle I should have perfect information about every packet being sent through it.

> Could you please explain a bit more what you are trying to do, which problem you are trying to solve?

The problem is that my `tap0` and `eth0` interfaces are being traffic shaped *separately*, but I require them to be traffic shaped *together* for IPv6 traffic (via `tap0`) to seamlessly integrated with IPv4 traffic (via `eth0`).

As it is right now, a surge in one device's traffic will lead to a degradation in service for the other device's traffic, because they are being considered independent by FireQOS when in reality they are not.

**Comment by ktsaou** [comment]
> But my PC is the VPN endpoint, so in principle I should have perfect information about every packet being sent through it.

No it is not. The kernel that applies QoS and the openvpn process are not one.

QoS is applied before anything else. If it is decrypted, unpacked, uncompresed, then it is already delivered and nothing can be done about it. At the point the kernel is applying QoS, it does have a clue about what the packet is and where it goes. I can only see the IP metadata (src, dst, protocol, etc) of the outer layer in its context (context = the interface the packet was received or sent).

QoS is about delaying (or even dropping) packets, **before they reach their destination** (destination in case is the openvpn process).

There is a patch in netdata (merged already), that uses GRE metadata to do what you suggest. But this works only because GRE uses a fixed offset in the packet to place a few of its metadata. Unfortunately (or better: fortunately for our security) this is not the case for openvpn.



> The problem is that my tap0 and eth0 interfaces are being traffic shaped separately, but I require them to be traffic shaped together for IPv6 traffic (via tap0) to seamlessly integrated with IPv4 traffic (via eth0).
> 
> As it is right now, a surge in one device's traffic will lead to a degradation in service for the other device's traffic, because they are being considered independent by FireQOS when in reality they are not.

The only solution I can think of, is to have a container (i.e. veth interface) receive both traffic and apply QoS after this is unencrypted. Like having a separate virtual host with a direct ethernet link. But it seems far too complex...

**Comment by haasn** [comment]
> No it is not. The kernel that applies QoS and the openvpn process are not one.

But I control both the kernel and the openvpn process, so in principle it should be possible to get them to communicate with one another. I'm not trying to say it's feasible, just that it shouldn't be impossible in principle.

> The only solution I can think of, is to have a container (i.e. veth interface) receive both traffic and apply QoS after this is unencrypted. Like having a separate virtual host with a direct ethernet link. But it seems far too complex...

I might end up having to route traffic through a custom veth one way or the other (see #151), so I'll keep it in mind. It sounds like a work-around that should work, if somewhat tricky to set up correctly.

**Comment by haasn** [comment]
This question has been sufficiently answered as far as I'm concerned.
