### ISSUE TITLE
Balance an interface by IP?

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#152]
I'm setting up a router for a small home network, and the goal is to not just apply traffic shaping based on packet category, but also fairly divide resources among users. This set up I have in mind is to do traffic shaping on the outbound link (using classes based on the packet type e.g. port) as well as on the inwards link (using classes based on the LAN IP).

Obviously I can go ahead and start enumerating classes for all of my clients, like

```
interface $LAN lan output balanced rate XYZ

    class user1
        match dst IP1
    class user2
        match dst IP2
    ....
```

but this does not scale well (manual effort, hits the class limit fairly quickly, etc.). Would it be somehow possible to instead have a balanced link where traffic is always fairly spit up among all IPs, without needing to create a class per IP?

**Comment by ktsaou** [comment]
In general `fq_codel`, the default qdisc in fireqos, does this automatically on a per-connection basis. So, all connections are balanced and short connections are favored over long running ones.

However, the above means that a host with 2 connections will use twice the bandwidth of a host with just one connection.

Another way is to set a cap like this:

```sh
class high prio 1
   for x in [1..254]; do match dst 10.0.0.${x} limit 50kbps; done

class low prio 2
  match dst 10.0.0.0/24

```

The above will allow all hosts to use 50kbps in `high` speed class. If they get more than that, the rest will be classified in `low` speed class. This will work even for packets of the same connection. You can also use this to limit possible floods in high priority classes (ie limit a DNS attack).

**Comment by haasn** [comment]
I've decided to solve this differently (by manually grouping together related IPs into subnets), so this question is answered as far as I'm concerned.
