### ISSUE TITLE
Two-level FireQoS setup: Evenly share bandwidth within each class?

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#154]
I'm trying to achieve the following two requirements with my FireQoS setup:

1. Prioritize all traffic according to the overall classification (e.g. voip > interactive > http > torrent etc.)

2. Divide traffic within each group fairly among users (of the router)

My configuration right now looks sort of like this:

```
interface macvlan-wan world bidirectional $LINKTYPE input rate $INPUT_SPEED output rate $OUTPUT_SPEED

    class voip commit 256kbit pfifo
    class interactive commit 5% output commit 5%
    class surfing commit 30% output commit 5% ceil 80%
    class default
    class torrents output ceil 10%
    # etc.
```

This classification works well for solving my first requirement. To try and further share traffic fairly among users, I tried using a second set of classes on the LAN interface like this:

```
interface macvlan-lan home bidirectional balanced input rate $OUTPUT_SPEED output rate $INPUT_SPEED

    class userA commit 25%
        match4 ip 192.168.0.0/24

    class userB commit 25%
        match4 ip 192.168.1.0/24

    # etc.
```

While the classification works (as per `fireqos status home-in`), the problem is that the traffic simply isn't split up fairly. If one user starts a fat download or something of that nature, the other users get barely 10% of the overall bandwidth (assuming both downloads fall into the same class e.g. surfing).

What am I doing wrong? Is there a better way to approach this problem? As a hard last resort I can use `ceil 25%` on each of the classes which gets me my desired fair subdivision under heavy load, but that's clearly undesirable since it means no single user can ever use the whole bandwidth even if it would otherwise be available.

**Comment by ktsaou** [comment]
hm... I don't think the way you do it will work. Each side (wan and lan) has buffers. QoS discs try not to drop traffic - they delay packets within the buffers. So, if the wan side buffer is full with user A packets, user B will simply be throttled together with user A at the wan side, so the lan side will not be able to detect it and fix it.

Generally, when using QoS you should make sure all the buffers in your path are empty, except of course the last one. This is why you have to lower the inbound rate of the wan side too: to empty the buffers of your ISP routers.

So, I think the only solution you have to have multi-level QoS at one side only, either wan or lan.

If you want to do it at the wan side, you cannot use the private IPs. You will have to map the local subnets to different ports on the wan side (using iptables SNAT or MASQUERADE) and match them at QoS using these ports.

**Comment by ktsaou** [comment]
This is very close to what you are trying to do: https://github.com/firehol/firehol/wiki/FireQOS-Use-Scenarios

**Comment by haasn** [comment]
That makes sense; moving it all to a single interface definition (via port mappings) allows me to do something like this:

```
class group surfing balanced input commit 30% output commit 10% ceil 80%
    class userA
        match sport 10000-19999
    class userB
        match sport 20000-29999
```

Unfortunately, doing it this way means I would need to effectively duplicate this construction for every single class. Oh well, it's only really `surfing` where fair distribution is important.

**Comment by ktsaou** [comment]
Use bash magic:

```sh

user_classes() {
    class userA
        match sport 10000-19999
    class userB
        match sport 20000-29999
}

class group blahblah balanced input commit 30% output commit 10% ceil 80%
    match ...
    user_classes
class group end

class group surfing balanced input commit 30% output commit 10% ceil 80%
    match ...
    user_classes
class group end

```
