### ISSUE TITLE
firehol: synproxy: command not found

### ISSUE THREAD

**Issue by mo0nsniper** [firehol/firehol#156]
Hello,

I have tryed to enable SYNPROXY on my server but I got an error.
I am currently running on this setup:
real server on the firewall itself, on the same port (e.g. SYNPROXY on port 80, real server on port 80 too)

So I've put the following lines in /etc/firehol.conf:
ipv4 synproxy input inface ens3 dst x.x.x.x dport 80 accept

interface ens3 wan
    server http accept

But when I try to activate the rules I get the following error:
[root@MIEZ:/etc/firehol ]# firehol start
FireHOL: Saving your old firewall to a temporary file:     [  OK  ]
FireHOL: Processing file /etc/firehol/firehol.conf:/usr/sbin/firehol: line 1057: synproxy: command not found
                                                           [  OK  ]
FireHOL: Activating new firewall (30 rules):               [  OK  ]

I am running fedora 23 and firehol is installed from the OS repository

**Comment by ktsaou** [comment]
hm... I think you have an old version of firehol. Please run it without any parameters to see its version. Is it v3?

**Comment by mo0nsniper** [comment]
FireHOL 2.0.1. It's the one included in fedora repo.

**Comment by ktsaou** [comment]
You can download and install the latest. It is very simple. This script can do it for you: https://github.com/firehol/netdata-demo-site/blob/master/install-all-firehol.sh

You may need to comment out the netdata part (as you already have it).

**Comment by ktsaou** [comment]
keep in mind iprange is required by firehol v3. So install it too.

**Comment by mo0nsniper** [comment]
Thanks I'll try it.

**Comment by mo0nsniper** [comment]
I have installed firehol using that script without netdata and it worked. Thank you.

**Comment by ktsaou** [comment]
nice!
