### ISSUE TITLE
Configuration not applied after autostart/reboot

### ISSUE THREAD

**Issue by freaky-m0** [firehol/firehol#157]
I have following in use:
Linux Mint 18.1 / Kernel 4.4.0-45-generic / Firehol 3.0.1 (from the deb-Package not repo)

I have a working firehol.conf in `/etc/firehol/firehol.conf`. All is fine if i start it with `firehol start`.
In the config file `/etc/default/firehol` i set `START_FIREHOL=YES`.
I also added it to autostart with `sudo update-rc.d firehol defaults`.

After i reboot i get the following:
`sudo service firehol status` >>

> ● firehol.service - LSB: firehol firewall configuration
   Loaded: loaded (/etc/init.d/firehol; bad; vendor preset: enabled)
   Active: active (exited) since So 2016-11-06 16:55:01 CET; 25s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1934 ExecStart=/etc/init.d/firehol start (code=exited, status=0/SUCCESS)
Nov 06 16:55:01 MintVM systemd[1]: Starting LSB: firehol firewall configuration...
Nov 06 16:55:01 MintVM systemd[1]: Started LSB: firehol firewall configuration.

`sudo iptables -t nat -nvL`

> Chain PREROUTING (policy ACCEPT 33 packets, 4853 bytes)
 pkts bytes target     prot opt in     out     source               destination         
******.... shows all empty...********

only when i run `sudo firehol start` my config will be applied:

> BLA....
Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            123.10.10.10/24     udp dpt:53 owner UID match 1234 ctstate NEW to:123.123.123.123
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            123.10.10.10/24     tcp dpt:53 owner UID match 1234 ctstate NEW to:123.123.123.123
(Numbers are fake)

I have no idea why it's not working with the autostart.

Any idea what's going wrong or what i am doing wrong?

**Comment by ktsaou** [comment]
2 possible reasons:

1. firehol does not start at all. From the log I can't tell. It gives an error but then it says that execstart completed with success. I don't know what this means.

2. firehol starts, but another service is started after firehol that alters the firewall.

I suggest to install the latest from github and use the systemd service found in the contrib directory.

**Comment by freaky-m0** [comment]
I think i fixed it.
Actually the package from `https://firehol.org/download/firehol/latest/` with `make install`.
To make autostart work correct i needed to change the file `/etc/init.d/firehol`.
I replaced all entries which said `/usr/sbin/firehol` with `/usr/local/sbin/firehol`.
Now i get the same results from the service, but my firehol.conf is activated.

> ● firehol.service - LSB: firehol firewall configuration
   Loaded: loaded (/etc/init.d/firehol; bad; vendor preset: enabled)
   Active: active (exited) since So 2016-11-06 23:24:27 CET; 3min 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1924 ExecStart=/etc/init.d/firehol start (code=exited, status=0/SUCCESS)
Nov 06 23:24:26 MintVM systemd[1]: Starting LSB: firehol firewall configuration...
Nov 06 23:24:27 MintVM systemd[1]: Started LSB: firehol firewall configuration.

`which firehol` >> `/usr/local/sbin/firehol`

I still think it's strange. If the path do the binary was wrong, why there were no errors. But now it works.

**Comment by ktsaou** [comment]
I don't know. This is distro related.
nice you solved it though.
