### ISSUE TITLE
`update-ipsets` doesn't seem to list some ipsets (?)

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#158]
I tried e.g. `update-ipsets enable country_cn`, but it doesn't get picked up by `update-ipsets`.

Indeed, the output of `update-ipsets` doesn't even seem to list `country_cn`: http://0x0.st/2V1.txt, among many others that are supposed to be included as per http://iplists.firehol.org/ and https://github.com/firehol/blocklist-ipsets

I'm not sure what I'm doing wrong, or why these ipsets don't seem to exist on my end. I've built `update-ipsets` from the latest git master.

**Comment by haasn** [comment]
Edit: Never mind, I see now that these are part of the meta-ipset `geolite2_country` etc.

It might be good to document this better.

**Comment by haasn** [comment]
Also, is there a more elegant way to enable these sub-ipsets than this?

```
for x in firehol_level1 firehol_level2
do
    ipset4 create  ${x} hash:net
    ipset4 addfile ${x} ipsets/${x}.netset
    blacklist4 input inface $WORLD ipset:${x}
done

for x in id_country_cn
do
    ipset4 create  ${x} hash:net
    ipset4 addfile ${x} ipsets/ipdeny_country/${x}.netset
    blacklist4 input inface $WORLD ipset:${x}
done
```

I tried just using `ipdeny_country/id_country_cn` as my `$x` but that gives me this error: `/usr/local/sbin/firehol: line 3498: /var/run/firehol/firehol-xJYd3qXL9N/ipset.ipdeny_country/id_country_cn.rules: No such file or directory`

Also, I'm not sure if I need to pick a special name to get it to be auto-updated by the kernel or not.

**Comment by ktsaou** [comment]
> Also, is there a more elegant way to enable these sub-ipsets than this?

unfortunately no. What you have done is the most elegant so far...

> In particular, I'm not sure if I need to pick a special name to get it to be auto-updated by the kernel or not.

The way you have done, I think it will be updated by `update-ipsets`. This is the reason why each country ipset has a unique name `country_cn`, `id_country_cn`, `ip_country_cn`, etc depending on the provider.
