### ISSUE TITLE
policy `forward` support?

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#162]
It would be great if I could have some sort of cascading firewall where I can have a declaration like this:

```
interface any private src4 "subnet"
   server foo accept
   policy forward world

interface any world
   server bar accept
   client all accept
```

The idea behind this configuration is that people inside the `private` subnet could access the `foo` service but also the `bar` service, without requiring duplication on my part.

In particular, I want to solve things this way because I'm trying to generate `firehol.conf` from a template, where one part will be global to all hosts and another part might be local to a single host. Being able to easily forward from a global `private` chain to my host-specific `world` chain would make things a lot easier.

Under the hood, this would work by having the `in_private` chain jump to `in_world` instead of a target like `REJECT` or `ACCEPT`.

**Comment by haasn** [comment]
Worth mentioning is that I “solved” this for my hand-written `firehol.conf` files by moving all of the `world` rules to a `common()` function instead and including this into every interface.

But I'm trying to clean this up and declaratively specify the list of interfaces for ansible-role-firehol, which doesn't seem cleanly possible without significant changes fo the ansible role.

**Comment by philwhineray** [comment]
I think you can do what you want by setting a custom policy on your earlier interface, i.e. try this form:

~~~~
interface4 any private src "subnet"
   policy return
   server foo accept

interface4 any private2 src "subnet2"
   policy return
   server foo2 accept

interface4 any world
   server bar accept
   client all accept
~~~~

Normally firehol would drop the packet at the end of the first matching interface but with a return we continue processing with the next matching one.

Note you could also just have the world interface and add multiple rules for the same service with different src constraints as needed.

**Comment by haasn** [comment]
@philwhineray Oh, that `return` policy seems like it's doing pretty much what I want.

**Comment by philwhineray** [comment]
That would be "the firehol way", I think. Can we close this issue?
