### ISSUE TITLE
transparent_proxy with ipv6

### ISSUE THREAD

**Issue by twnaing** [firehol/firehol#164]
With

    transparent_proxy 80 3128

gives out the following problem

```
ERROR   : # 1.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : 10@/etc/firehol/firehol.conf: transparent_proxy:
COMMAND : /bin/ip6tables -t nat -A out_trproxy.1 -p tcp \! -d 127.0.0.1 -j REDIRECT --to-ports 3128
OUTPUT  :

ip6tables v1.6.0: host/network `127.0.0.1' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
```

However with 

    transparent_proxy 80 3128 ""

or

    ipv4 transparent_proxy 80 3128 proxy

I can apply the changes. I think there the firehol-proxy helper is not generating correct iptables rule for ipv6

**Comment by philwhineray** [comment]
You are correct. I have pushed a fix to the master branch - are you able to check it works for you?

**Comment by twnaing** [comment]
I am using stable release 3.01 on ArchLinux. I don't have git based installation and so I will manually modify and post the result here.
