### ISSUE TITLE
ip6tables v1.4.21: invalid port/service `2230,4573' specified

### ISSUE THREAD

**Issue by wefixit-AT** [firehol/firehol#169]
I get the following error when I apply the rules which are posted below:

> ERROR   : # 4.
> WHAT    : A runtime command failed to execute (returned error 2).
> SOURCE  : line 120 of /etc/firehol/firehol.conf
> COMMAND : /sbin/ip6tables -t filter -A out_lan0wan_gSsh_s9 -p tcp --sport 2230\,4573 --dport 1024:65535 -m conntrack --ctstate ESTABLISHED -j ACCEPT 
> OUTPUT  : 
> 
> ip6tables v1.4.21: invalid port/service `2230,4573' specified
> Try `ip6tables -h' or 'ip6tables --help' for more information.

These are my service definition:
```
server_gSsh_ports="tcp/2230,4573"
client_gSsh_ports="default"
```

These are my route defintion:
```
router lan0wan inface $DEV_LAN0 outface $DEV_WAN
    masquerade
    route gSsh accept
```

The same fule for ipv4 gives the same error message:
```
router lan0wan inface $DEV_LAN0 outface $DEV_WAN
    masquerade
    route4 gSsh accept
```

Centos 7: 3.10.0-327.36.2.el7.x86_64
firehol-2.0.1-1.el7.noarch

**Comment by ktsaou** [comment]
Hi, this is not supported for firehol 2.0.1.
You have to write it as:

```
server_gSsh_ports="tcp/2230 tcp/4573"
```

Version 3+ of firehol accepts the new format.

**Comment by wefixit-AT** [comment]
Thanks for the quick response, this solves the "problem"
