### ISSUE TITLE
Create systemd service file

### ISSUE THREAD

**Issue by lkraav** [firehol/firehol#17]
Probably not much else to say here

**Comment by philwhineray** [comment]
Finally got around to it... sorry for the delay!

**Comment by SanskritFritz** [comment]
I ran into a problem with this service on boot, namely that Firehol failed to start, because it was started too early, before the network. The reason was this line:
```
server ssh accept with limit 10/m 100 overflow drop src "example.domain.com"
```
DNS didn't resolve the domain name yet, so IPtables complained:
```
iptables v1.6.0: host/network `example.domain.com' not found
```
I solved this by putting the following into firehol.service:
```[Unit]
Description=Firehol stateful packet filtering firewall builder
Documentation=man:firehol(1)
Requires=network.target
After=network.target
```
I'd like to hear your comments on that and if you agree, could you please include those lines? I very much can imagine that this is not wanted, as Firehol should be started as early as possible.

**Comment by philwhineray** [comment]
I certainly think the firewall should come up before the network if at all possible. Some things (anything sunrpc, like NFS) so make that really difficullt.

Using a hostname in the config is a pretty bad idea in general. You might be able to do something with ipsets instead?

**Comment by SanskritFritz** [comment]
> I certainly think the firewall should come up before the network if at all possible.

Yes, I thought so and theoretically agree.

> Using a hostname in the config is a pretty bad idea in general. You might be able to do something with ipsets instead?

The reason I'm using a hostname is that the IP address is dynamic, handled by freedns.afraid.org.
ipsets sounds good, but the ISP doesn't constrain the IP addresses to me. So I don't have any other idea how to constrain the src tag with a dynamic IP address.

**Comment by ktsaou** [comment]
> So I don't have any other idea how to constrain the src tag with a dynamic IP address.

You can do this if you use an ipset as `src` and have a cron job update the ipset regularly...

**Comment by SanskritFritz** [comment]
I'll look into this, thank you.

**Comment by philwhineray** [comment]
It's worth noting that using a hostname doesn't create a dynamic firewall;
iptables just substitutes the IP addresses at load time, so you'd need to
run firehol in a cron job anyway. If you can use ipsets they are a much
better solution.
