### ISSUE TITLE
FireHol and DD-WRT

### ISSUE THREAD

**Issue by uihdff** [firehol/firehol#170]
Are there instructions for installing FireHOL on DD-WRT ?

**Comment by philwhineray** [comment]
Not that I know of. If you already saw the [installation instructions for FireHOL on OpenWRT](https://firehol.org/installing/openwrt/), the basics are probably quite similar to that.

The biggest dependency for FireHOL is probably bash. If you can get that installed you will definitely be able to run the configure script successfully and it should tell you anything else missing.

Happy to help where I can in this ticket, and if we get you going and you fancy doing a short write-up, I'd be thrilled to publish it on the website.
