### ISSUE TITLE
Working with ipsets / netsets

### ISSUE THREAD

**Issue by tomschlenkhoff** [firehol/firehol#171]
When working with multiple ip/netsets (say from iplists.firehol.org) it would be a lot easier to work with them if they all would be ending in say "*.netset", like "iblocklist_isp_att.netset".

I tried simply renaming all *.ipset files to *.netset and thereby reducing script complexity to:
do
	ipset4 create  ${x} hash:net
	ipset4 addfile ${x} ipsets/${x}.netset
	blacklist4 input inface eth3 log "BLOCK ${x^^}" ipset:${x}
done

1.) Does this "renaming approach" have any disadvantages?
2.) If not, can't we simply treat *.ipset files as "flat" *.netset files?

**Comment by ktsaou** [comment]
Well, this actually breaks all old kernels (prior to 3.11 I believe).
In these versions of the kernel, there was no way to load an ipset to a hash:net. The kernel refused to do it.

Also, in the kernel, `hash:net` ipsets are expensive, meaning that the kernel is maintaining a list of multiple `hash:ip` ipsets for each `hash:net` ipset and it looks up each IP in each of the linked ipsets.

It is not an elegant solution, from a performance standpoint...

**Comment by tomschlenkhoff** [comment]
Thanks, didn't know about the kernel/performance implications. Just saw that it worked. Will adjust, though.
