### ISSUE TITLE
CentOS 7: Upgrade to v3

### ISSUE THREAD

**Issue by wefixit-AT** [firehol/firehol#172]
Is there a safe way to upgrade from v2, which comes from the epel repository, to v3?

**Comment by ktsaou** [comment]
Well, you can install the latest version of all tools of firehol.org using these commands:

```sh
# install all the required packages on your system
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' -o /tmp/kickstart.sh && bash /tmp/kickstart.sh -i firehol-all netdata

# install firehol, iprange and netdata
# source will be installed in `/usr/src`
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-all-firehol.sh' -o /tmp/firehol-install.sh && sudo bash /tmp/firehol-install.sh
```

Most of the v2 configuration can be used by v3. But I would suggest to test your v2 configuration on a non-production server with v3, before upgrading a running server.

**Comment by wefixit-AT** [comment]
Today I had some time to Upgrade. It works flawless and reduce my rule counter from 1753 rules to 1328 rules + the change time (firehol start) reduced from 6 minutes to 22seconds
