### ISSUE TITLE
ICMP port unreachable

### ISSUE THREAD

**Issue by faust64** [firehol/firehol#175]
Hi,

I'm pretty new to firehol, and may have missed something.
I'm using firehol on several debian instances (installed from jessie repository).
Said systems are hosted on a couple physical servers. Each physical server has a public IPv4 subnet arriving on a bridge. Instances network interfaces are configured with /32, default gateway is the KVM hypervisor, ...

Now say I have a mail instance and a monitoring instance on the same physical server, with their public IPs in the same /29 subnet.

On my mail instance, Firehol configuration would look like

```
version 5
office_networks="trustedIP1 trustedIP2 trustedIPN"
interface eth0 WAN
	server icmp accept
	server smtp accept
	server smtps accept
	server https accept
	server custom openssh "tcp/1234" default accept
	server custom munin "tcp/4949" default accept src "$office_networks"
	server custom nrpe "tcp/5666" default accept src "$office_networks"
	client all accept
```

I would the expect that my monitoring server could check SMTP service availability, as `server smtp accept` *should* allow in everything.

Yet with this configuration, having my monitoring server IP included in the `office_network` alias, I can't connect to my mail server's SMTP port. I can ping the mail server, I can connect to my SSH port, ... But I get a connection refused, using telnet, connecting to my SMTP server.

Using tcpdump on my KVM server, it appears that an ICMP port unreachable is returned.
I had no troubles checking SMTP availability on my second mail instance, hosted on my second physical server/in my second public subnet.
Not a single instances from my first public subnet was able to forward their emails to my first relay.
Removing my monitor IP from `office_networks` did fix SMTP, although my monitor could no longer connect to tcp/5666.

Now, restoring my configuration to the first sample and adding:
```
	server smtp accept src "$office_networks"
```

Then and only then, my monitoring server can reach my mail server's SMTP port.

How's that? Is that a bug?

**Comment by ktsaou** [comment]
Hi,

You are probably using an ancient version of firehol.

Even so, all versions of firehol log all packets they drop indirectly (i.e. not dropped by a `drop` or `reject` statements). So, it would be very helpful if you find these iptables logs.
