### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by LiveChief** [firehol/firehol#176]
the "Install the whole firehol suite" isnt working for Debian for some reason as soon as i execute it my ssh windows closes.

@ktsaou @philwhineray 

=========================================================================
Fix:
https://ghostbin.com/paste/v68rj
can someone please check/verify this

# What did i change?
>Removed all the "|| exit 1"

## Whats happens when you execute the script?
>>https://ghostbin.com/paste/qhktc

**Comment by philwhineray** [comment]
Sorry to hear you are having problems.

You have provided too little information to help so far.

What (if anything) have you downloaded, how did you install and exactly
what commands are you running?

**Comment by LiveChief** [comment]
Sorry for not explaining it properly, now that i actually read it i cant even tell what i wrote LOL

Anyway
So the Current script which includes "exit 1" isn't working with Debian 8, so as soon as the part of the script "exit 1" comes up Debian takes it as to force user and close session (SSH), so what i am suggesting is we take out that part (EXIT 1) and leave the script like that, i just need someone else to check if it works on other installs or not (without EXIT 1).

**Comment by philwhineray** [comment]
OK, I understand.

Which script are you referring to, though, and what exactly are you typing to run it?

It sounds like you are sourcing the script where maybe you should be running it as a separate process but I need the above to be sure.

**Comment by LiveChief** [comment]
This was on my first post :/

"the "Install the whole firehol suite" isnt working for Debian for some reason as soon as i execute it my ssh windows closes."

https://github.com/firehol/firehol/wiki/Install-the-whole-firehol-suite

**Comment by philwhineray** [comment]
Thanks for the link - I haven't seen that wiki page before, so you will understand my confusion!

I recommend you save the script to a file e.g. `install-fh.sh` and run it as:

~~~~
bash install-fh.sh
~~~~

Then your shell won't exit and you will see the error.

I will get the page updated to make this clear.

**Comment by philwhineray** [comment]
Also, up until now I have bee replying direct to the emails sent by github. Did you edit your first post? Most of that information did not come through... Github doesn't send a new email when a post is updated. If it was all there originally, I guess it truncated it where you put the ==== line, all I saw was what came before, sorry.

**Comment by LiveChief** [comment]
root@www-streamingeverywhere-com:/usr/src# bash install-fh.sh
Downloading (git pull) iprange...
Already up-to-date.
Downloading (git pull) firehol...
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.
    git pull <remote> <branch>
root@www-streamingeverywhere-com:/usr/src#

**Comment by philwhineray** [comment]
Something seems not as expected with your `/usr/src/firehol.git` tree. Did you ever run any commands in it manually?

If not, or if you don't care about any changes in there, then you can probably just delete it. Otherwise, you will need to somehow reset it to the master branch.

**Comment by LiveChief** [comment]
https://ghostbin.com/paste/v68rj

**Comment by philwhineray** [comment]
Removing the exit commands allows the script to run to completion and install something but since the git pull did not work, there is no guarantee what it installed.

Based on the error and exit in the original script, you need to bring `/usr/src/firehol.git` into a known state. Unless you have something you want to save in that folder, the quickest way to do it is to delete it, which is to say:

~~~~
rm -r /usr/src/firehol.git
~~~~

Then re-run the original script. The exit commands are there to protect from problems earlier in the process resulting in a broken installation later.

**Comment by LiveChief** [comment]
worked :)
Thanks
