### ISSUE TITLE
Arch Linux packaging broken

### ISSUE THREAD

**Issue by pavel** [firehol/firehol#178]
### Environment
OS: Arch Linux
Installation way: [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages)
Versions affected: since 3.1.0, particularly since [this change to sbin/Makefile.am](https://github.com/firehol/firehol/commit/caedbcd5512aa61caa3c62b90581023a1915516f#diff-bc2d3e0adc894d2fb1196166e7a6f511)

### To reproduce

1. Install `firehol` or `firehol-git` from AUR.

### Problem
Binaries (e.g. /usr/bin/firehol) are symlinked to the build directory.

### Cause
As stated [here](https://wiki.archlinux.org/index.php/creating_packages#package.28.29) (see the last note in the linked section "package()"):
> Note: Creating symlinks is a slightly awkward process in the package() function. Using the naive approach ln -s "${pkgdir}/from/foo" "${pkgdir}/to/goo" will result in a broken symlink to the build directory. The way to create a proper link is to create it pointing to an initially-broken source, ln -s "/from/foo" "${pkgdir}/to/goo". Once the package is installed, the link will point to the right place.

, symlinking that happens inside arch linux's `package()` function is incorrect. Problem is in [sbin/Makefile.am line 51](https://github.com/firehol/firehol/blob/b19df5dc4dd3c5a5550b5157d3a89adb188d8550/sbin/Makefile.am#L51). For Archlinux it should say:
```bash
$(LN_S) "$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
```
Applying this change worked for me.

---

I have a feeling that changing this to the "Arch Linux way" will break other distros.

@SanskritFritz You as a package maintainer is probably interested in this ticket too.

**Comment by SanskritFritz** [comment]
Thanks for the heads-up. How come I have never realised this, is beyond me. Well, I never delete the build dir, that would explain it.
Merry Christmas! I just spent 5 minutes on the computer, don't worry, I'm with the kids playing Jungle Speed 😃

**Comment by SanskritFritz** [comment]
Even namcap gives an error, shame on me:
```
frank@HomeC ~/B/a/S/firehol> namcap firehol-2:3.1.0-1-any.pkg.tar
firehol E: Symlink (usr/bin/vnetbuild) points to non-existing /home/frank/Builds/aur4/SanskritFritz/firehol/pkg/firehol/usr/lib/firehol/3.1.0/vnetbuild
firehol E: Symlink (usr/bin/update-ipsets) points to non-existing /home/frank/Builds/aur4/SanskritFritz/firehol/pkg/firehol/usr/lib/firehol/3.1.0/update-ipsets
firehol E: Symlink (usr/bin/fireqos) points to non-existing /home/frank/Builds/aur4/SanskritFritz/firehol/pkg/firehol/usr/lib/firehol/3.1.0/fireqos
firehol E: Symlink (usr/bin/link-balancer) points to non-existing /home/frank/Builds/aur4/SanskritFritz/firehol/pkg/firehol/usr/lib/firehol/3.1.0/link-balancer
firehol E: Symlink (usr/bin/firehol) points to non-existing /home/frank/Builds/aur4/SanskritFritz/firehol/pkg/firehol/usr/lib/firehol/3.1.0/firehol
firehol W: Package was 60% docs by size; maybe you should split out a docs package
```

**Comment by SanskritFritz** [comment]
I solved this temporarily by manually creating the symlinks.

**Comment by vahem2lu** [comment]
I can confirm bug here as well.

**Comment by SanskritFritz** [comment]
> Problem is in sbin/Makefile.am line 51. For Archlinux it should say:
> $(LN_S) "$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
> I have a feeling that changing this to the "Arch Linux way" will break other distros.

Honestly I don't see why this would break other distros, the original line 
```$(LN_S) -r "$(DESTDIR)$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done```
is inherently wrong in my opinion, since the the link should not point to $DESTDIR anyway but to the (yes, distro dependent) lib directory which happens to be /usr/lib in archlinux.

**Comment by ktsaou** [comment]
I know @philwhineray will be busy until the weekend, so let's wait for him...

**Comment by philwhineray** [comment]
The change is in just-released v.3.1.3 - @SanskritFritz can you close this when you are happy it has worked for you. Thanks!

**Comment by SanskritFritz** [comment]
Yes, thank you. I have updated the archlinux package as well. I'm afraid I can't close this issue, as I'm not the owner or OP. @pavel please install Firehol 3.1.3 from the AUR and confirm the fix.

**Comment by pavel** [comment]
Installed "firehol" (version 3.1.3) package from AUR. It works.
> ls -la $(which firehol)
> /usr/bin/firehol -> ../lib/firehol/3.1.3/firehol

> readlink -f $(which firehol)
> /usr/lib/firehol/3.1.3/firehol
