### ISSUE TITLE
Performance limits (1753 rules)

### ISSUE THREAD

**Issue by wefixit-AT** [firehol/firehol#186]
Hi,

my firehol.conf generates currently 1753 rules. The server runs as virtual machine with the following specifications:

- CentOS 7.3
- firehol-2.0.1-1.el7.noarch
- 1GB memory, about 500mb used
- It acts as gateway for 5 networks in a small environment with less traffic

The startup of firehol took about 5-7 minutes, for test purpose I run this command:

`time firehol start`

To speed it up I added the virtual machine 1, 2 and 4 CPU cores but the time did not change. It varies between 5 and 7 minutes.

What are the limits of firehol?
Should I split it to more hosts do decrease the rules per installation or how can I improve the performance?

On another network with 350 rules, with better hardware, the startup time is very good.

greetings
gregor

**Comment by ktsaou** [comment]
Please use firehol v3 - it is a lot faster.

In v2 the default is to execute iptables commands, one after another. v3 generates a file that is loaded with `iptables-restore`. Also v3 has a ton of optimizations, especially for speed.

**Comment by wefixit-AT** [comment]
I upgraded like in #172 described and the rules reduced to 1328 + the time are reduced to 22 seconds. awesome.
