### ISSUE TITLE
Firehol configuration fails if host has dash in the name. 

### ISSUE THREAD

**Issue by Alekc** [firehol/firehol#199]
Following line in configuration will make firehol startup fail:

`server all accept src "x-2.example.com"`

Full error is 
```
ERROR   : # 8.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : 21@/etc/firehol/gw.conf: server:
COMMAND : /sbin/iptables -t filter -A out_wan1 -m iprange --dst-range x-2.example.com -m conntrack --ctstate RELATED\,ESTABLISHED -m helper --helper sip -j ACCEPT
OUTPUT  :

iptables v1.4.21: iprange: Bad value for "--dst-range" option: "x"
Try `iptables -h' or 'iptables --help' for more information.

```

Looks like firehol parser sees the dash and it's trying to treat this command as ip range splitting x-2.example.com in "x" and "2.example.com"

This was working fine in standard firehol on jessie

```
aptitude show firehol
Package: firehol
State: installed
Automatically installed: no
Version: 1.297-1
Priority: optional
Section: net
Maintainer: Jerome Benoit <calculus@rezozer.net>
Architecture: all
Uncompressed Size: 705 k
Depends: iptables (>= 1.4.14), iproute2, bash (>= 4.2), lsb-base
Recommends: kmod, wget | curl, aggregate
Suggests: ulogd2
Description: easy to use but powerful iptables stateful firewall
 FireHOL generates generic firewalls with an extremely simple but powerful configuration language, enabling you to design any kind of local or routing stateful packet
 filtering firewall with ease.

 FireHOL does not (yet) support ipv6.

 FireHOL is reviving and will support ipv6 in the coming new major release.
Homepage: http://firehol.org

Tags: implemented-in::shell, interface::daemon, network::firewall, network::server, role::program, security::firewall, use::configuring

```

But it fails on FireHOL 3.1.1

**Comment by philwhineray** [comment]
Thanks for the report. You are correct - the code is spotting the `-` and using e.g. `--dst-range` when communicating with iptables, rather than simple `--dst`.

I will look at what can be done to improve this, however I recommend you move away from using domain names in your firewall configuration if at all possible: they are not robust for a number of reasons.

The modern solution would be to use an [ipset](https://firehol.org/guides/ipset/) instead. Then you will avoid problems with DNS resolution, dynamic IPs not being tracked and more.

**Comment by philwhineray** [comment]
Aha, I knew there was an earlier conversation relating to the dangers of DNS domain names in configs. It is [here](/firehol/firehol/issues/17#issuecomment-270394467).

**Comment by Alekc** [comment]
Yeah there are some danger but it kind of make sense in small environment. I could go through the route of generating iplist dynamically if I ever have dynamic dns but for now I am more than happy with manual startup of firewall and dns resolution on the start. 

As for possible fix of this issue, what about checking the first character? If I am not wrong, spec (http://www.ietf.org/rfc/rfc1034.txt) says that 

```
The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.
```

So if first character is not a digit then it's probably a dns entry.

**Comment by philwhineray** [comment]
Well l certainly intend to fix it but my recommendation stands regardless.

Having read the code, the main problem is that we make the match with
simple shell globbing but it needs to apply to both ipv4 and ipv6, so a
simple character check is inadequate.

**Comment by philwhineray** [comment]
I think this will work:

*-* =>
  *:*-*  == IPv6 range
  [0-9]*-*  == IPv4/IPv6 range

Then any remaining dashes cannot be part of a valid range, therefore
we treat them as a single value and let iptables do what it wants, as
usual.

**Comment by philwhineray** [comment]
Didn't realise this would auto-close...

@Alekc and @de-es are you in a position to check if this change fixes the problem for you before I make a release of it?

**Comment by de-es** [comment]
The problem is fixed for me (tested ipv4 only). Thank you very much.
