### ISSUE TITLE
patch proposal

### ISSUE THREAD

**Issue by kneeke** [firehol/firehol#201]
problem:
create symlinks (for example /sbin/firehol) without the 'relative' parameter 
causes problems when using 'make install DESTDIR=<...>'

cause:
the symlinks inside the package created _at_ DESTDIR will still have a path 
_to_ DESTDIR, which will fail once the package is installed elsewhere and/or 
DESTDIR is removed

solution:
use '-r' to indicate relative paths, see patch

```
diff -u -r firehol-3.1.2-orig/sbin/Makefile.am firehol-3.1.2/sbin/Makefile.am
--- firehol-3.1.2-orig/sbin/Makefile.am	2017-02-05 09:44:24.000000000 +0100
+++ firehol-3.1.2/sbin/Makefile.am	2017-02-10 08:13:06.205336928 +0100
@@ -48,7 +48,7 @@
 	$(CHMOD) 755 "$(DESTDIR)$(sbindir)"
 	for i in $(scripts); do \
 		$(RM) -f "$(DESTDIR)$(sbindir)/$$i"; \
-		$(LN_S) "$(DESTDIR)$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
+		$(LN_S) -r "$(DESTDIR)$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
 
 uninstall-hook:
 	for i in $(scripts); do \
diff -u -r firehol-3.1.2-orig/sbin/Makefile.in firehol-3.1.2/sbin/Makefile.in
--- firehol-3.1.2-orig/sbin/Makefile.in	2017-02-05 09:46:09.000000000 +0100
+++ firehol-3.1.2/sbin/Makefile.in	2017-02-10 08:14:43.343575133 +0100
@@ -609,7 +609,7 @@
 	$(CHMOD) 755 "$(DESTDIR)$(sbindir)"
 	for i in $(scripts); do \
 		$(RM) -f "$(DESTDIR)$(sbindir)/$$i"; \
-		$(LN_S) "$(DESTDIR)$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
+		$(LN_S) -r "$(DESTDIR)$(inclibdir)/$$i" "$(DESTDIR)$(sbindir)"; done
 
 uninstall-hook:
 	for i in $(scripts); do \
```

**Comment by philwhineray** [comment]
Thanks.

Unfortunately, not all versions of `ln` support the `-r` flag (certainly busybox can be built without it) so we will need to perform a proper check and only use it where available.

@SanskritFritz will this change also solve #178 ?

**Comment by SanskritFritz** [comment]
> @SanskritFritz will this change also solve #178 ?
No, making the link relative does not solve the problem of the link pointing to the source file rather than $DESTDIR. I'll make a comment at #178 as well.

**Comment by SanskritFritz** [comment]
I thought about this a bit and I can say this actually solves the problem if the directory structure is like /usr/bin and /usr/lib. But that would not be distro agnostic.

**Comment by philwhineray** [comment]
To change the organisation, change the params to `./configure` so that `make install` puts the chosen locations. Then, as far as I can see it will always do the right thing as the final tree is organised the same way as it is installed under DESTDIR, even if it is moved elsewhere later.

Ran a quick check setting values for `--libexecdir` on `./configure` to unusual directories and that confirmed it for me. That leaves the question of systems which do not have `-r` (which maybe just can't support DESTDIR properly) and detecting if we can use the parameter in the configure script.

**Comment by SanskritFritz** [comment]
This is what I use:
```  ./configure --prefix=/usr --sbindir=/usr/bin --sysconfdir=/etc --libexecdir=/usr/lib```
I wanted to say it would not work if I set --sbindir=/opt/bin, but after testing it, I have to say this actually works well. So I revert my statement above, and confirm that the -r switch does solve issue #178.

**Comment by philwhineray** [comment]
OK. I'm closing this. The change is in v3.1.3.
