### ISSUE TITLE
Unable to install firehol

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/firehol#206]
I have downloaded tar file of firehol(firehol-3.1.3.tar.gz) and then unzipped it.

I am facing problem in installing iit.

When I run `./configure` , it says(at the end)

.
.
..
..
checking for screen... no
checking for traceroute... no
configure: error: cannot find required executable, bailing out

**Comment by philwhineray** [comment]
You need to install the programs that are missing. i.e `traceroute` in this case.

Or, if you don't need `link-balancer` (which is the only program in the package which uses `traceroute` you can use the `--disable-link-balancer` option on the `./configure` command.

**Comment by sLuvpreet33** [comment]
What does this link balancer do?
And I got another error,

checking for git... /usr/bin/git
checking for ipset... no
configure: error: cannot find required executable, bailing out

**Comment by philwhineray** [comment]
See this [wiki page about link-balancer](https://github.com/firehol/firehol/wiki/Link-Balancer)

Configure is telling you that you need to install the `ipset` command.

**Comment by ktsaou** [comment]
A simpler way (like netdata):

```
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i firehol netdata
```

The above will give you all the packages you need to install to your system to install netdata and firehol.

Then you can use this to install all firehol.org programs (firehol, fireqos, iprange, netdata) to your system: https://github.com/firehol/netdata-demo-site/blob/master/install-all-firehol.sh

**Comment by sLuvpreet33** [comment]
That curl command didn't seem to work.
But Thank you very much for the github script. It is working.

**Comment by ktsaou** [comment]
> That curl command didn't seem to work.

Can you post the output? I should fix it...

**Comment by sLuvpreet33** [comment]
Yeah, this is what I got.

The Apache error log may have more information.
invoke-rc.d: initscript apache2, action "reload" failed.
dpkg: error processing package gosa (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of gosa-plugin-nagios:
 gosa-plugin-nagios depends on gosa; however:
  Package gosa is not configured yet.

dpkg: error processing package gosa-plugin-nagios (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          Errors were encountered while processing:
 gosa
 gosa-plugin-nagios
E: Sub-process /usr/bin/dpkg returned an error code (1)



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues

**Comment by sLuvpreet33** [comment]
Another thing is, I want to monitor any specific port through netdata on my system.

Like Fireqos does, it is showing me the default, ssh and other services' traffic. Now, ssh is running on port 22, means it is monitoring the ssh port(22).
Now suppose, if I want to see the traffic on port 8008(django server port), can I do that using Fireqos ?

I am trying to learn the Fireqos using this -- https://github.com/firehol/firehol/wiki/FireQOS-Tutorial
But haven't got it yet clearly. Like what is interface ? Linktype?

**Comment by ktsaou** [comment]
qos can provide quite a few features. They are discussed here: https://github.com/firehol/netdata/wiki/You-should-install-QoS-on-all-your-servers

You will need to give it some time to understand why it is used.

**Comment by sLuvpreet33** [comment]
Okay now I am getting some hack of it.

Device means the network card which I am using.
and classes will be shown in the netdata graphs, means I can put different
ports into one class and see there traffic.

Now,
1.   is there any kind of list for these class names or I can create my own
class name?

2. is there any restriction that ports can be put under specific classes,
like is there something like surfing class can only take ports from 0-1023
and not any other port?

3. Under interactive class, I wrote this --  match tcp port 80 , and it
showed me the interactive class on netdata page. But then I started django
server on port 8000, and replaced port 80 with 8000 under interactive
class, and it didn't show interactive class on netdata page then, why so ?

4. Now ,how should I write it ? dport 8000 sport 8000 or port 8000 ?

**Comment by sLuvpreet33** [comment]
https://bpaste.net/show/1d60304a0e17

here is my fireqos.conf file.

Interactive remains on 0 even if my django server is running on 8000 port
and I am making requests to it, and it is serving those requests
succesfully.
Then why it doesn't show any traffic?

**Comment by ktsaou** [comment]
I think you have mixed sports/dports. You use `sports` for the inbound direction, so you are matching the source ports of the packets are coming in, which are the port of the clients attempting to connect to your 8000. These are not going to be 8000. Similarly for the other direction.
