### ISSUE TITLE
update-ipsets disabled on gentoo

### ISSUE THREAD

**Issue by ktsaou** [firehol/firehol#207]
@alonbl I see here: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-firewall/firehol/firehol-3.1.3.ebuild#n49 that update-ipsets is disabled.

I have user requests for update-ipsets on gentoo: http://iplists.firehol.org/?ipset=firehol_level1#comment-3196254855

**Comment by alonbl** [comment]
This net-firewall/ipset is not available on arm, but I masked it.
Added.
Not sure I can actually support that.

**Comment by ktsaou** [comment]
> This net-firewall/ipset is not available on arm

hm... why? Is there a limitation that prevents it from being available?
`ipset` should also be required by firehol (or several directives will fail).

**Comment by alonbl** [comment]
On 10 March 2017 at 20:18, Costa Tsaousis <notifications@github.com> wrote:
>
> This net-firewall/ipset is not available on arm
>
> hm... why? Is there a limitation that prevents it from being available?
> ipset should also be required by firehol (or several directives will fail).

I do not see ipset mandatory, if it is mandatory please modify
autoconf to at least warn.
For now I support this using ipset USE flag in archs that supports ipset.

**Comment by ktsaou** [comment]
ok. thanks!
