### ISSUE TITLE
Wiki: Install the whole firehol suite

### ISSUE THREAD

**Issue by svengo** [firehol/firehol#209]
Hi,

I installed the whole firehol suite using the guide in the [wiki](https://github.com/firehol/firehol/wiki/Install-the-whole-firehol-suite). The autoconf script is called with `./configure --prefix=/usr --sysconfdir=/etc --disable-man --disable-doc || exit 1` which leads to [Netdata bug 1684](https://github.com/firehol/netdata/issues/1684) since `--localstatedir=/var` is not set. Without this setting the runtime data goes to `/usr/var` which doesn't make any sense to me.

Could you please change the wiki article?

Thank you!
Sven

**Comment by ktsaou** [comment]
Thanks I updated it! I also added a link to the version we maintain on git.
