### ISSUE TITLE
bad link in wiki

### ISSUE THREAD

**Issue by llunaCreixent** [firehol/firehol#218]
Hi!
In FirQOS use scenarios (https://github.com/firehol/firehol/wiki/FireQOS-Use-Scenarios), in the first paragraph, the link to 'FireQOS Tutorial' should be (https://github.com/firehol/firehol/wiki/FireQOS-Tutorial) and not (https://github.com/ktsaou/firehol/wiki)
Regards

**Comment by ktsaou** [comment]
thanks! fixed it.
