### ISSUE TITLE
partner with filterlists.com

### ISSUE THREAD

**Issue by jawz101** [firehol/firehol#226]
https://github.com/collinbarrett/FilterLists
https://filterlists.com
maintains a list of common DNS blocklists and adblock syntax around the web

I was wondering if the same http://iplists.firehol.org/ analysis could be applied to DNS blocklists and, possibly, adblocker syntax (easylist or Adblock syntax are pretty universal bases)

[Adblock syntax](https://adblockplus.org/filters) and [this](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)
[Ublock syntax](https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions)
[Adguard syntax notes](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

It would be nice to see how DNS blocklists overlap and how well they are maintained.

Personally, I use all 3 blocking methods (Firehol lists, DNS blocklists and Easylist) in a pfSense package called [pfblocker-ng](https://forum.pfsense.org/index.php?topic=115357.0) for wide coverage.

for IP filtering I use several of ipfilter's consolidated blocklists, for DNS I use [StevenBlack](https://github.com/StevenBlack/hosts)'s consolidated host file, and [Easylist](https://easylist.to/) for specific web filtering.

**Comment by ktsaou** [comment]
Hi.

Nice compilation of lists!

I guess hostnames and URLs could be correlated in a way to find evolution, retention policy, age of entries listed, overlaps among different lists, even the validity of URLs (i.e. are they reachable?).

However this is quite a different project. If I can help, I'll be glad to, but I can't take over this task on my own. iplists.firehol.org required several months of work to be completed, and currently I can't give that much time to another project (given that https://my-netdata.io is already quite demanding).

**Comment by jawz101** [comment]
ok... That netdata looks awesome.  You have quite a talent.
