### ISSUE TITLE
Class not matching IPv6 tunnel

### ISSUE THREAD

**Issue by MikeLund** [firehol/firehol#234]
Hi, I am having trouble with fireqos classifying traffic that comes in through my v4tunnel.

Short example, I have this as fireqos.conf:
```
DEVICE=eth0
INPUT_SPEED=30000kbit                                                                                                                                          OUTPUT_SPEED=5000kbit                                                                                                                                          
LINKTYPE="ethernet"                                                                                                                                             
interface $DEVICE world-in input rate $INPUT_SPEED $LINKTYPE                                                                                                   interface $DEVICE world-out output rate $OUTPUT_SPEED $LINKTYPE
                                                                                                                                                               
interface $DEVICE world-in input rate $INPUT_SPEED $LINKTYPE balanced                                                                                          
   class http commit 20%                                                                                                                                             
      match tcp port 80                                                                                                                                   

   class default               

interface $DEVICE world-out output rate $OUTPUT_SPEED $LINKTYPE balanced 
   class http commit 20%                                                                                                                                             
      match tcp port 80                                                                                                                                

   class default               
```

But all this traffic is instead being classified into the default class for some reason, confirming by doing `fireqos dump world-in default`:

> IP tserv1.nyc4.he.net > my-public-hostname: IP6 2002:b442:6346::b442:6346.53744 > my-public-hostname.http: Flags [P.], seq 0:324, ack 1, win 257, length 324: HTTP: GET /....

Is there some silly mistake I am doing? Thanks!

**Comment by ktsaou** [comment]
I am not using IPv6.
@philwhineray can you help?

**Comment by philwhineray** [comment]
For `fireqos` you need to specify `interface46` explicitly to get IPv6 and IPv4 matching. The default is just IPv4.

Also, I don't know if it is just a copy-paste error but you seem to have defined the `world-in` interface twice?

**Comment by ktsaou** [comment]
> For fireqos you need to specify interface46 explicitly to get IPv6 and IPv4 matching. The default is just IPv4.

( oops! I didn't recall that! thanks @philwhineray )

**Comment by MikeLund** [comment]
Hey again, thanks for the reply!

> you need to specify `interface46` explicitly to get IPv6 and IPv4 matching

Ah, is this because of some technical limitation? If I use `interface46`, I get "I don't know how to match SYNs in ipv6" (since I added also the synacks class).

Anyways, if I remove the synacks so I can use `interface46`, it still seems like the `http` class isn't catching stuff from my v6 tunnel. If I dump the `http` class, I see all the traffic there is v4; all that v6 http traffic is still falling into `default`.

Perhaps I am doing something wrong with $DEVICE? I am only setting rules on eth0, and the v6 tunnel is its own interface. But all the traffic passes through eth0, so I would think it would work, but I'm very inexperienced with this type of thing. Thanks again and hope there's something else I can debug with! :)

**Comment by philwhineray** [comment]
The tunneling will be the problem, hopefully I can explain why.

When a packet goes into a tunnel, it gets wrapped in a different packet
with different properties and is then resent through the main device. The
reverse process happens and the packet is unwrapped at the other end.

This means QoS on your main device sees only the tunnel endpoint values
when it looks for addresses, ports etc.

I don't use a tunnel to be able to help. I guess the interaction with QoS
generally might be quite complex if you want to try to manage such
encapsulated traffic.

**Comment by MikeLund** [comment]
That makes sense. Assume it won't be easy or even possible to be fixed then. Will close this issue, thanks again for your time!
