### ISSUE TITLE
FireQOS match tcp doesn't do anything

### ISSUE THREAD

**Issue by mikenor** [firehol/firehol#249]
Using, FireQOS 3.1.3 when I configure a class that has `match tcp` or `match protocol tcp`, the resulting `tc filter` command is missing the appropriate match statement. According to FireQOS debug mode, the resulting `tc` command is `tc filter add dev eth0 parent 1:0 protocol ip prio 10 flowid 1:11`. **Shouldn't the `tc` command contain `match ip protocol 6` somewhere?**

**Comment by ktsaou** [comment]
Thanks for reporting it.
It seems the GRE patches messed this up.
Fixed it.

**Comment by ktsaou** [comment]
merged it!
Thank you for reporting it!
