### ISSUE TITLE
FireQos does not launch at startup

### ISSUE THREAD

**Issue by sebLopezCot** [firehol/firehol#250]
On one of my ubuntu 16.04 machines, I installed iptables and FireHol via make. FireQoS seems to work fine when I run "sudo fireqos start", but when I add it to my crontab to run at reboot, it fails. I have been trying to get the START_FIREHOL flag to work, but doesn't seem to do much. How is one supposed to launch fireqos from startup?

**Comment by ktsaou** [comment]
Hi,

in the contrib directory, you can find `fireqos.service`. Copy it to `/etc/systemd/system` and run `systemctl enable fireqos`.

**Comment by sebLopezCot** [comment]
I have done as you have recommended. After rebooting, I run `systemctl status fireqos` and get this log:

● fireqos.service - FireQOS traffic shaping for humans
   Loaded: loaded (/etc/systemd/system/fireqos.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-08-16 20:46:32 UTC; 5s ago
     Docs: man:fireqos(1)
           man:fireqos.conf(5)
  Process: 1175 ExecStart=/usr/sbin/fireqos start (code=exited, status=203/EXEC)
 Main PID: 1175 (code=exited, status=203/EXEC)

Aug 16 20:46:32 ip-172-31-57-242 systemd[1]: Starting FireQOS traffic shaping for humans...
Aug 16 20:46:32 ip-172-31-57-242 systemd[1]: fireqos.service: Main process exited, code=exited, status=203/EXEC
Aug 16 20:46:32 ip-172-31-57-242 systemd[1]: Failed to start FireQOS traffic shaping for humans.
Aug 16 20:46:32 ip-172-31-57-242 systemd[1]: fireqos.service: Unit entered failed state.
Aug 16 20:46:32 ip-172-31-57-242 systemd[1]: fireqos.service: Failed with result 'exit-code'.


My fireqos.conf is located in /usr/local/etc/firehol/fireqos.conf and is the following:

DEVICE=eth0
OUTPUT_SPEED=16000kbit

interface $DEVICE world-out output rate $OUTPUT_SPEED

Any thoughts?

**Comment by ktsaou** [comment]
The `fireqos.service` file assumes fireqos is in `/usr/sbin/fireqos`.

1. Edit it to set the right path
2. execute `sudo systemctl daemon-reload` to reload it
3. execute `sydo systemctl start fireqos` to start it.

Does it work now?

**Comment by sebLopezCot** [comment]
Yes, that solve the problem. Thanks!
