### ISSUE TITLE
firehol startup under systemd has to be delayed for conntrack to be initialized

### ISSUE THREAD

**Issue by ktsaou** [firehol/firehol#260]
@philwhineray on a debian 8 system I have this problem:

When the system boots, firehol tries to start but it fails, because the conntrack module is not given enough time to initialize itself. My guess is that because systemd starts up everything in parallel, firehol loads the conntrack module, but it fails to be initialized on time.

To overcome this issue, I had to add this:

```
ok=60
while [ $ok -ne 0 ]
do
  	ok=$(( ok - 1 ))
        sysctl -w net/netfilter/nf_conntrack_tcp_loose=0 && ok=0
        [ $ok -ne 0 ] && sleep 1
done
```

So, this waits for the specific sysctl to be available before continuing.

Any ideas if there is a better way to do it?

**Comment by andvgal** [comment]
For me it produces a warning "This might or might not affect the operation of your firewall".

In my case, these sysctl values are also set through sysctl.conf by provisioning system ([cfnetwork](https://forge.puppet.com/codingfuture/cfnetwork) + [cffirehol](https://forge.puppet.com/codingfuture/cffirehol)). They usually fail at sysctl invocation as well, so I force "/sbin/sysctl -p" in /etc/rc.local once more time. Of course, all that is dirty workaround.

But please, if you decide to change it somehow, please please please make sure the firewall is activated first. 

I can propose the following approach:
1. Try to setup sysctl and record failures
2. Activate firewall as normal.
3. If there was any sysctl failure, try to wait with reasonable timeout to retry sysctl configuration. Do not fail on error.

**Comment by philwhineray** [comment]
I don't think that any of the sysctl values we set affect the loading of rules, only runtime behaviour.

With that in mind I think @andvgal could be onto something. Always loading the rules sounds like a good idea. It might be easier to just move the sysctl calls with timeout to be last in processing, rather than testing for failure eariler and retrying. This way the module gets most time possible to initialise before we start slowing things down.

Having said that, how sure are that this is the problem? Why is it happening only for this module and not others? Presumably it would be catastrophic if the iptables module was not ready. Should we maybe always wait, after we load one or more modules?


How much timeout did you actually need? 60 seconds sounds excessive, so should it be maybe be more like 5s, with a 0.1s or 0.2s increment? Note that some embedded systems won't take decimal sleep times though, so we'd need to test for it, shift to 1s increments.

**Comment by philwhineray** [comment]
On the subject of waiting for all modules... Do most tools deal with waiting for the modules to finish initialising? The sysctl command just looks for a file under `/proc`, so it may be more sensitive to timing than other things but I am pretty sure we use some special netfilter files directly in firehol.

**Comment by ktsaou** [comment]
I just tried to trace this in the code.

firehol loads kernel modules at `prepare_firewall_for_activation()`, just before activating the firewall. It does:

```sh
prepare_firewall_for_activation() {
	load_kernel_module ip_tables
	load_kernel_module nf_conntrack
	if [ $ENABLE_IPV6 -eq 1 ]
	then
		load_kernel_module ip6_tables
	fi
	
	for m in ${!FIREHOL_KERNEL_MODULES[*]}
	do
		postprocess -ne -ns load_kernel_module $m
	done
```

and then it flushes the chains the runs the activation.

For sure there are a few loops involved and a few external command run, so there should be plenty of time for the kernel module to be activated.

So, I edited `firehol.service` to log to a file the output of firehol. I rebooted a few times:

---

## 1st reboot

```
# cat /root/firehol.log
WARNING: error initializing iptables: IPv4 disabled
 WARNING: error initializing ip6tables: IPv6 disabled
 ERROR: Neither IPv4 nor IPv6 is available - exiting
```

---

## 2nd and 3rd reboot

(it worked)

```sh
# cat /root/firehol.log 
FireHOL: Saving active firewall to a temporary file...  OK 
FireHOL: Processing file '/etc/firehol/firehol.conf'...  OK  (281 iptables rules)
FireHOL: Activating ipsets...  OK 
FireHOL: Fast activating new firewall...  OK 
FireHOL: Saving activated firewall to '/var/spool/firehol'...  OK 
```

---

## 4th reboot

```sh
# cat /root/firehol.log 
 WARNING: error initializing iptables: IPv4 disabled
FireHOL: Saving active firewall to a temporary file...  OK 
FireHOL: Processing file '/etc/firehol/firehol.conf'... 
--------------------------------------------------------------------------------
 ERROR : # 1
WHEN   : Initializing
WHY    :  Cannot use namespace ipv4 within ipv6 
COMMAND: \(unset\) 
MODE   : ipv6
SOURCE : 30@/etc/firehol/firehol.conf: synproxy4:


--------------------------------------------------------------------------------
 ERROR : # 2
WHEN   : Initializing
WHY    :  Cannot use namespace ipv4 within ipv6 
COMMAND: \(unset\) 
MODE   : ipv6
SOURCE : 33@/etc/firehol/firehol.conf: masquerade4:


--------------------------------------------------------------------------------
 ERROR : # 3
WHEN   : Initializing
WHY    :  Cannot use namespace ipv4 within ipv6 
COMMAND: \(unset\) 
MODE   : ipv6
SOURCE : 42@/etc/firehol/firehol.conf: ipset4:


--------------------------------------------------------------------------------
 ERROR : # 4
WHEN   : Initializing
WHY    :  Cannot use namespace ipv4 within ipv6 
COMMAND: \(unset\) 
MODE   : ipv6
SOURCE : 43@/etc/firehol/firehol.conf: ipset4:

[iptables rules: 79 |]  FAILED 


NOTICE: No changes made to your firewall.

FireHOL: Restoring old firewall...  OK 
```

hm... something very strange is happening...

**Comment by ktsaou** [comment]
As you can see, on 1st reboot firehol thinks ipv4 and ipv6 are disabled, and on 4th reboot firehol thinks ipv4 is disabled.

**Comment by ktsaou** [comment]
To detect is ipv4 or ipv6 are disabled, firehol runs:

```sh
# ipv4
iptables -nxvL

# ipv6
ip6tables -nxvL
```

If these commands return non zero, firehol believes the corresponding network stack is disabled.

**Comment by ktsaou** [comment]
Well, I tried to catch the output of the iptables command that fails, and I got this:

```
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```

And here is what `-w` does:

```
       -w, --wait
              Wait for the xtables lock.  To prevent multiple instances of the  program  from  running  concur‐
              rently,  an  attempt will be made to obtain an exclusive lock at launch.  By default, the program
              will exit if the lock cannot be obtained.  This option will  make  the  program  wait  until  the
              exclusive lock can be obtained.
```

Testing with it.

**Comment by philwhineray** [comment]
Seems timing related. Clearly modprobe returns and sometimes things are ready for the next steps and sometimes not.

I would add a short sleep after the modprobe to see if that appears to solve it. I don't know if there is an official way to wait for a module to complete its initialisation after it is instructed to load.

If systemd is starting many thing in parallel, maybe they are all trying to load modules and these are getting queued up - that might explain why this has not been seen before. Or maybe the modprobe and/or kernel behaviour is changed to initialise asynchronously.

**Comment by andvgal** [comment]
AFAIR. Debian package starts after network. It's the reason, I use custom systemd unit start Before "network-pre".
Also, there is known Debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864341

**Comment by philwhineray** [comment]
@andvgal - thanks, that bug report sounds like the same thing, indeed. Not sure why we are only seeing it now though.

@ktsaou do you have any other (default, perhaps) firewall-loading services also installed? I guess maybe the lock is not available during initialisation but maybe something else also wants it.

**Comment by ktsaou** [comment]
I think it is related to containers. I see that before firehol is started I have these:

```
       0        0 ACCEPT     all  --  *      lxcbr0  0.0.0.0/0            0.0.0.0/0           
       0        0 ACCEPT     all  --  lxcbr0 *       0.0.0.0/0            0.0.0.0/0    
```

I guess `docker` does the same.

Adding `-w` to these iptables command, fixes it for me.

**Comment by ktsaou** [comment]
Still `synproxy` requires that loop at `rc.local`, otherwise it does not work. I guess something else tweaks that setting too.

**Comment by philwhineray** [comment]
Can you determine what message you get in that case, from sysctl? The bug @andvgal linked to has the exact same behaviour and they seem to have determined it is because the files do not yet exist. The error message will allow us to confirm.

**Comment by ktsaou** [comment]
Here it is:

```
sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_tcp_loose: No such file or directory
retrying 59...
net.netfilter.nf_conntrack_tcp_loose = 0
```

This loop logged that:

```sh
ok=60
while [ $ok -ne 0 ]
do
        ok=$(( ok - 1 ))
        sysctl -w net/netfilter/nf_conntrack_tcp_loose=0 && ok=0
        [ $ok -ne 0 ] && sleep 1 && echo "retrying ${ok}..."
done >/root/rclocal.log 2>&1
```

**Comment by philwhineray** [comment]
As the file does not exist, I think [comment 30 in the bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864341#30) is correct.

That still leaves us with a problem in FireHOL though. I think a delay loop, looking for `/proc/sys/net/netfilter/nf_conntrack_tcp_loose` to exist after loading the module would be best, since it solves the problem where it is caused, i.e. by that particular module.

And I guess we should be adding the -w flag to the iptables commands to try to stop us racing with other processes, although the answer to that is probably to modify the service to ensure it does not run at the same time as docker, libvirt or anything else that might create its own rules. I won't have time to look at that, sorry.

**Comment by ktsaou** [comment]
made PR #261 that fixes all the issues mentioned above.

**Comment by ktsaou** [comment]
@andvgal this has been merged.
I would love to get some feedback from you.

**Comment by andvgal** [comment]
@ktsaou I keep this one my list, I'll try to find some time tomorrow to test in vagrant VMs.

**Comment by andvgal** [comment]
@ktsaou I have verified master build in test infrastructure.. However, I couldn't reproduce the original problem on old version with only new service unit file (it was pre-changed in cffirehol module).

Maybe the following lines hide the problem or there are different timings in virtualized environment.
```
Wants=systemd-modules-load.service local-fs.target
After=systemd-modules-load.service local-fs.target
```

I've seen the original problem in production for sure. The changes in PR look quite reasonable.

**Comment by philwhineray** [comment]
I've created #279 which changes the file which is looked for because the one in the #261 PR does not exist when running in a namespace.

Hopefully the new file should work both with/without namespaces but I have not commited the PR as I hope someone can check it works for them before I do.
