### ISSUE TITLE
firehol not starting on most major distributions

### ISSUE THREAD

**Issue by uDuCkV** [firehol/firehol#264]
I am not able to start firehol from the latest pull on Ubuntu16, Centos6, RHEL7.

```
# firehol try
 WARNING: error initializing iptables: IPv4 disabled
 WARNING: error initializing ip6tables: IPv6 disabled
 ERROR: Neither IPv4 nor IPv6 is available - exiting

```

Debian 8 is still working. 

The problem seams to be the following arguments on iptables commands:

```
+ /sbin/iptables **-wnxvL**
+ '[' 2 -ne 0 ']'
+ echo ' WARNING: error initializing iptables: IPv4 disabled'
 WARNING: error initializing iptables: IPv4 disabled
```

```
iptables -wnxvL
iptables v1.4.21: wait seconds not numeric
Try `iptables -h' or 'iptables --help' for more information.
```

Correcting the above to the following seams to work.

`iptables -w 1 -nxvL`

**Comment by ktsaou** [comment]
Let me check:

```sh
# iptables --version
iptables v1.4.21

# iptables -w 10 -nxvL; echo $?
Bad argument `10'
Try `iptables -h' or 'iptables --help' for more information.
2

# iptables -wnxvL; echo $?
# output cut - works
0
```

or another system:

```sh
# iptables --version
iptables v1.6.1

# iptables -w 10 -nxvL; echo $?
# output cut - works
0

# iptables -wnxvL; echo $?
iptables v1.6.1: wait seconds not numeric
Try `iptables -h' or 'iptables --help' for more information.
2
```

So, I think this will work on both:

```sh
# iptables --version; iptables -wnxvL >/dev/null || iptables -w 10 -nxvL >/dev/null; echo $?
iptables v1.4.21
0

# iptables --version; iptables -wnxvL >/dev/null || iptables -w 10 -nxvL >/dev/null; echo $?
iptables v1.6.1
iptables v1.6.1: wait seconds not numeric
Try `iptables -h' or 'iptables --help' for more information.
0
```

Making a PR now...

**Comment by ktsaou** [comment]
@philwhineray we will need to release this asap.
I will merge it once travis finishes.

**Comment by ktsaou** [comment]
merged it

**Comment by philwhineray** [comment]
This only got broken in git, I don't think there is an existing release with the problem.

I agree we need a release soon anyway but it's not really an asap in my opinion.

**Comment by ktsaou** [comment]
well, it is on Arch (and all its derivatives), on Ubuntu 16.10+ and I guess a lot more.

I think ubuntu 16.10+ (all the ubuntu releases of the last year) are the breaking point here.

**Comment by philwhineray** [comment]
No, what I mean is the -w flag was only added in git, never released, so only people running git master between when you added the flag and now are affected.

**Comment by ktsaou** [comment]
ooops! Does this mean we have to add a command without `-w` at all?

**Comment by ktsaou** [comment]
Oh! you mean firehol release! ok.

**Comment by uDuCkV** [comment]
Default iptables (1.4.7) package on Centos 6.9, does not support "--wait" flag at all.
