### ISSUE TITLE
maxmind_proxy_fraud not working

### ISSUE THREAD

**Issue by mmccarn** [firehol/firehol#265]
The URL for maxmind_proxy_fraud (https://www.maxmind.com/en/anonymous-proxy-fraudulent-ip-address-list) redirects to https://www.maxmind.com/en/high-risk-ip-sample-list

The new page does not have any links matching the $GREP_CMD on line 3501:
```
parse_maxmind_proxy_fraud() {
        $GREP_CMD "href=\"proxy" |\
                $CUT_CMD -d '>' -f 2 |\
                $CUT_CMD -d '<' -f 1
}
```

Changing $GREP_CMD as shown below allows generation of maxmind_proxy_fraud.ipset - but I don't know if the resulting IP set matches the description any more...
```
parse_maxmind_proxy_fraud() {
        $GREP_CMD "href=\"high-risk" |\
                $CUT_CMD -d '>' -f 2 |\
                $CUT_CMD -d '<' -f 1
}
```

**Comment by ktsaou** [comment]
thanks!

fixed in #267

**Comment by bunder2015** [comment]
They seem to have changed the format again, I had to edit mine to `/en/high-risk-ip-sample/`

**Comment by mmccarn** [comment]
```
# diff -u update-ipsets- update-ipsets
--- update-ipsets-	2019-09-21 10:33:23.683548561 -0400
+++ update-ipsets	2019-09-21 10:34:03.325093583 -0400
@@ -3616,7 +3616,7 @@
 
 # extract IPs from the maxmind proxy fraud page
 parse_maxmind_proxy_fraud() {
-	$GREP_CMD "href=\"high-risk-ip-sample/" |\
+	$GREP_CMD "href=\"/en/high-risk-ip-sample/" |\
 		$CUT_CMD -d '>' -f 2 |\
 		$CUT_CMD -d '<' -f 1
 }
```
