### ISSUE TITLE
shunlist (autoshun.org) now requires registration and API key

### ISSUE THREAD

**Issue by mmccarn** [firehol/firehol#266]
Enabling shunlist generates 'shunlist.source' like this:
`Please register for your subscription to this data at https://www.autoshun.org/register/`

Registering generates a new, unique URL to use for csv download that looks like this:
`https://www.autoshun.org/download/?api_key=<my-api-key-goes-here>&format=csv`

editing /usr/sbin/update-ipsets to use the new URL solves the problem, but isn't a particularly useful long-term solution...

One option that occurs to me is to add support for a ".conf" file for each blocklist formatted as 
`ARG <whitespace> VALUE`

Then modify the update function to use the value from the conf file if there is one.

Specifically, for shunlist, this would look like this:

1) modify the update function like this:
```
 	local 	ipset="${1}" mins="${2}" history_mins="${3}" ipv="${4}" limit="${5}" \
-			url="${6}" \
+			defurl="${6}" \
 			processor="${7-$CAT_CMD}" \
 			category="${8}" \
 			info="${9}" \
-			maintainer="${10}" maintainer_url="${11}"
+			maintainer="${10}" maintainer_url="${11}" \
+			confurl=$(awk '/URL/ {print $2}' ${ipset}.conf)
 	shift 11
-
+	local url=${confurl:-$defurl}
```

2) create 'shunlist.conf' in the ipsets folder containing
`URL "https://www.autoshun.org/download/?api_key=<my-api-key-goes-here>&format=csv"`

**Comment by ktsaou** [comment]
thanks!

fixed with #267
