### ISSUE TITLE
zfs writes are not monitored

### ISSUE THREAD

**Issue by diched** [firehol/firehol#270]
Hi,

Just created a simple stripe zfs pool with 
zpool create -f zfspool sdb sdc sdd

And ran bonnie++ on it. The netdata showed read activity instead of write (but lower throughput than in reality). 

Anyone else seen a similar problem? 

Thanks

**Comment by ktsaou** [comment]
wrong repo. You have submitted this to firehol (the firewall) :)
Open it at netdata and please state the O/S, distro.

**Comment by diched** [comment]
Oops, sorry!

**Comment by ktsaou** [comment]
Did you open it? I don't see it.

**Comment by diched** [comment]
Now yes! :)
