### ISSUE TITLE
v3.1.5 missing docker_ bridge changes

### ISSUE THREAD

**Issue by jonnyt886** [firehol/firehol#271]
I was eager to test out your new `docker_bridge` functionality (#262) but although this merge appears to have been included in the 3.1.5 release according to github, that release doesn't actually include the changes:

    $ wget https://github.com/firehol/firehol/releases/download/v3.1.5/firehol-3.1.5.tar.gz
    $ tar zxf firehol-3.1.5.tar.gz           
    $ grep docker_bridge firehol-3.1.5/sbin/*
    $

...and sure enough it doesn't find `docker_bridge`:

    $ sudo firehol restart
    FireHOL: Saving active firewall to a temporary file...  OK
    FireHOL: Processing file '/etc/firehol/firehol.conf'... /etc/firehol/firehol.conf: line 3: docker_bridge: command not found
     OK  (246 iptables rules)
    FireHOL: Fast activating new firewall...  OK
    FireHOL: Saving activated firewall to '/usr/var/spool/firehol'...  OK

I wonder whether the wrong tag was used when cutting the release builds?

**Comment by philwhineray** [comment]
Hi

v3.1.5 preceded that fix by about a week.

I'll try to put together a new release before long but for now the answer is to use git master.
