### ISSUE TITLE
Question: log capability

### ISSUE THREAD

**Issue by pavel** [firehol/firehol#293]
On [a wiki page regarding `iptrap`](https://github.com/firehol/firehol/wiki/Working-with-traps) there's a mention of a command `log`.
I tried to find any information about this useful command, but was not able to.
Is there any document I can look at to know details of the `log` command?

**Comment by ktsaou** [comment]
log is among the standard parameters on all commands: https://firehol.org/firehol-manual/firehol-params/

**Comment by pavel** [comment]
@ktsaou Thanks!
