### ISSUE TITLE
enabling fireqos not working

### ISSUE THREAD

**Issue by nemethdani** [firehol/firehol#315]
When I enable fireqos.service with systemctl, traffic shaping doesn't seem to work. When I start the service by hand after boot, everything woks fine.

systemctl status fireqos
● fireqos.service - FireQOS traffic shaping for humans
   Loaded: loaded (/usr/lib/systemd/system/fireqos.service; enabled; vendor pres
   Active: active (exited) since Thu 2018-02-22 21:08:21 CET; 1min 7s ago
     Docs: man:fireqos(1)
           man:fireqos.conf(5)
  Process: 493 ExecStart=/usr/sbin/fireqos start (code=exited, status=0/SUCCESS)
 Main PID: 493 (code=exited, status=0/SUCCESS)

febr 22 21:08:21 dani-pc fireqos[493]: :         class torrents (1:18, 12/962kbi
febr 22 21:08:21 dani-pc fireqos[493]: :         committed rate 768kbit (79%), t
febr 22 21:08:21 dani-pc fireqos[493]:   Traffic is classified:
febr 22 21:08:21 dani-pc fireqos[493]:       - on 1 interfaces
febr 22 21:08:21 dani-pc fireqos[493]:       - to 8 classes
febr 22 21:08:21 dani-pc fireqos[493]:       - by 18 FireQOS matches
febr 22 21:08:21 dani-pc fireqos[493]:   79 TC commands executed
febr 22 21:08:21 dani-pc fireqos[493]: All Done! Enjoy...
febr 22 21:08:21 dani-pc systemd[1]: Started FireQOS traffic shaping for humans.
febr 22 21:08:21 dani-pc fireqos[493]: bye...

The errorous output:

sudo fireqos status world-out
FireQOS 3.1.6_master
(C) 2013-2014 Costa Tsaousis, GPL

world-out: enp2s0f0 output => enp2s0f0, type: ethernet, overhead: 
Rate: 962Kbit/s, min: 12Kbit/s
Values in Kbit/s

 CLASS   voip intera faceti   vpns surfin synack defaul torren 
CLASSI   1:11   1:12   1:13   1:14   1:15   1:16 1:8000   1:18 
COMMIT    100    192    200    192     48     12     12     12 
   MAX    962    962    962    962    962    962    962    962 

PRIORI      0      1      2      3      4      5      6      7 
 QDISC fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod 

 color code (packets):  backlog  |  dropped  |  delayed  |  requeued 
 Class Utilization on world-out (enp2s0f0 output => enp2s0f0) - values in Kbit/s
 TOTAL   voip intera faceti   vpns surfin synack defaul torren 
 ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR 
 ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR 
 ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR  ERROR

**Comment by ktsaou** [comment]
QoS can only be applied after the system has setup the network interfaces.
I guess this means we need to instruct systemd to wait for network before starting fireqos.
Let me check how to do this...

**Comment by ktsaou** [comment]
In PR #329 
Can you test it?

**Comment by nemethdani** [comment]
Unfortunately, this didn't solve the issue for me (I am using manjaro linux by the way). I also noticed that after a system wakeup, I get the same errors, so I need to stop and restart fireqos manually.

**Comment by ktsaou** [comment]
ok, I am out of ideas.

1. on boot: there should be systemd setting that would delay startup of a service, until the host has operational networking.
2. on wakeup: there should be something (I guess ACPI related) to run a script when the device wakes up.

Can you research them a bit?

**Comment by nemethdani** [comment]
Solved:
Along with your commit, I also had to enable a system-specific service. More info here: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
For me on Manjaro, I had to enable NetworkManager-wait-online.service
With this and your updated fireqos.service file, fireqos is started on startup.
From here, it should be easier to handle the sleep-wakeup problem.

**Comment by nemethdani** [comment]
for resumse, a new service is created:
[Unit]
Description=FireQOS resume after sleep
Documentation=man:fireqos(1) man:fireqos.conf(5)
After=suspend.target


[Service]
Type=oneshot
ExecStart=/usr/bin/nm-online -q --timeout=30
ExecStartPost=/usr/bin/systemctl restart fireqos.service

[Install]
WantedBy=suspend.target
