### ISSUE TITLE
Fireqos shows only delayed traffic

### ISSUE THREAD

**Issue by pinkflozd** [firehol/firehol#327]
Hello. I've been using fireqos for years on Arch linux.
A month or so ago fireqos stopped showing and also shaping class traffic.
I did try to recompile firehol+fireqos and also use the git version.
The "Total" number gets painted purple as delayed.
I did try to use a base config and the effect is the same.
How could i debug it?
Journalctl doesn't show nothing suspicious either

FireQOS 3.1.5
(C) 2013-2014 Costa Tsaousis, GPL

adsl-in: enp4s0 input => enp4s0-ifb, type: adsl, overhead: 0
Rate: 29000Kbit/s, min: 290Kbit/s
Values in Kbit/s

 CLASS     t2 realti  cccam  oscam mining   iptv iptvou headen    web surfin synack defaul    p2p 
CLASSI   1:11   1:12   1:13   1:14   1:15   1:16   1:17   1:18   1:19   1:20   1:21 1:8000   1:23 
COMMIT  17000    290    290    290    290   6000    290    290    290   1000    290    512    290 
   MAX  29000  29000  29000  29000  29000  29000  29000  29000  29000  29000  29000  29000  29000 

PRIORI      0      1      1      1      1      2      3      4      4      4      5      6      7 
 QDISC fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod fq_cod 

 color code (packets):  backlog  |  dropped  |  delayed  |  requeued 
 Class Utilization on adsl-in (enp4s0 input => enp4s0-ifb) - values in Kbit/s
 TOTAL     t2 realti  cccam  oscam mining   iptv iptvou headen    web surfin synack defaul    p2p 
  7395      -      -      -      -      -      -      -      -      -      -      -      -      - 
 10949      -      -      -      -      -      -      -      -      -      -      -      -      - 
  8710      -      -      -      -      -      -      -      -      -      -      -      -      - 
 11096      -      -      -      -      -      -      -      -      -      -      -      -      - 
  8638      -      -      -      -      -      -      -      -      -      -      -      -      - 
  8502      -      -      -      -      -      -      -      -      -      -      -      -      - 
  8615      -      -      -      -      -      -      -      -      -      -      -      -      - 
  8733      -      -      -      -      -      -      -      -      -      -      -      -      - 
  5877      -      -      -      -      -      -      -      -      -      -      -      -      - 
  7325      -      -      -      -      -      -      -      -      -      -      -      -      - 
  7591      -      -      -      -      -      -      -      -      -      -      -      -      -
 `

**Comment by ktsaou** [comment]
There is an issue in the latest iproute package - it gives faulty output omitting a few required parameters.
I have provided a work-around with #318 (so fireqos now parses the buggy iproute output too).

If you use the latest git version of fireqos, it should work.

**Comment by Smarre** [comment]
Using newest stable version (3.1.6), I’m getting all delayed packets too. Is there any way to inspect this?
