### ISSUE TITLE
Allow disabling documentation build

### ISSUE THREAD

**Issue by dodgex** [firehol/firehol#33]
Hello,

i'm trying to build a deb of latest firehol for my servers but even a simple call to `make` fails due to a missing rule.

> make[2]: Entering directory `/path/to/firehol/doc'
> make[2]: *** Keine Regel vorhanden, um das Target »service-links«,
> benötigt von »all-local«, zu erstellen.  Schluss.

in the doc/Makefile there is that rule but commented out
```
#service-links: $(FIREHOLIN) services-db.data
#        $(MKSERVICELINKS) service-links $+
```

if i uncomment that lines i get

> make[2]: Entering directory `/path/to/firehol/doc'
> service-links services-db.data
> /bin/bash: service-links: Kommando nicht gefunden.

when checking what value `$(MKSERVICELINKS)` has i found
```
#MKSERVICELINKS = ${top_srcdir}/doc/tools/mkservicelinks
#FIREHOLIN = $(top_srcdir)/sbin/firehol.in
```

uncommenting this results in the next error...

> make[2]: Entering directory `/path/to/firehol/doc/firehol'
> make[2]: *** Keine Regel vorhanden, um das Target »man/man1/firehol.1«,
>  benötigt von »all-am«, zu erstellen.  Schluss.

and there is again a hell of lines commented out... and i wonder why?

**Comment by philwhineray** [comment]
Latest master has two options to the configure script:

* `--disable-doc`
* `--disable-man`

Supply them both and pandoc is no longer needed (but you get no documentation).
