### ISSUE TITLE
FireQOS and ipsets

### ISSUE THREAD

**Issue by sereeds** [firehol/firehol#353]
Can I use ipsets in my FireQOS configuration?
If so, can you please provide an example.

Here is a snippet of my fireqos.conf.  Can we make an equivalent config with ipsets and iprange?

```
  class winupdates min 500 max 3000
    match host 40.76.0.0/14   prio 2
    match host 40.96.0.0/12   prio 2
    match host 40.124.0.0/16  prio 2
    match host 40.120.0.0/14  prio 2
    match host 40.112.0.0/13  prio 2
    match host 40.125.0.0/17  prio 2
    match host 40.74.0.0/15   prio 2
    match host 40.80.0.0/12   prio 2
    match host 13.96.0.0/13   prio 2
    match host 13.104.0.0/14  prio 2
    match host 13.64.0.0/11   prio 2
```

My fireqos.conf file is getting rather large and I would like to use ipsets from my own file:
ipsets/winupdates1.netset

Is that possible?

**Comment by ktsaou** [comment]
Unfortunately the kernel does not allow tc rules to access ipsets (at least I haven't found any documentation for this - if you can, please correct me and I'll support it in fireqos).

For outbound traffic shaping you can mark the traffic using firehol (iptables) and then use the mark in fireqos (tc) to classify the traffic. Unfortunately, it does not work for inbound traffic (qos handles the traffic before iptables - so even connmark will not work).

A simpler alternative is this:

```sh
winupdate_ips="40.76.0.0/14  40.96.0.0/12  40.124.0.0/16 40.120.0.0/14 40.112.0.0/13 40.125.0.0/17 40.74.0.0/15  40.80.0.0/12  13.96.0.0/13  13.104.0.0/14 13.64.0.0/11"

class winupdates min 500 max 3000
    match host "${winupdate_ips}" prio 2
```

**Comment by sereeds** [comment]
OK that's fine.  
I tested, and both your alternatives worked good.

The fact that the config is shell script is amazing.  I can do some cool stuff with that.  Possibly reference my private ipset from a central server if I wanted.  Really neat.

Thank you.

**Comment by ktsaou** [comment]
> The fact that the config is shell script is amazing. I can do some cool stuff with that. Possibly reference my private ipset from a central server if I wanted. Really neat.

Yes, that is the idea...

**Comment by ktsaou** [comment]
btw, firehol config is also a shell script :)
