### ISSUE TITLE
how to show Firehol blacklist matches on Netdata

### ISSUE THREAD

**Issue by sereeds** [firehol/firehol#354]
I am using firehol and netdata, with the firehol level 1 iplist:

Snippet from the firehol.conf
```
ipset4 create firehol_level1 hash:net
ipset4 addfile firehol_level1 ipsets/firehol_level1.netset
#blacklist4 input inface eth0 log "BLACKLIST firehol_level1" ipset:firehol_level1
blacklist4 full inface eth0 ipset:firehol_level1
```
What is the proper way to show a netdata graph of the firehol level1 blacklist hits/matches per second etc. ?

**Comment by ktsaou** [comment]
you can use NFACCT. netdata has an nfacct module, but unfortunately this requires running netdata as root.

So, in firehol you can use:

```sh
blacklist4 full inface eth0 ipset:firehol_level1 accounting blacklisted
```

After running netdata as root, you will have this section:

![image](https://user-images.githubusercontent.com/2662304/42530103-f95c9b08-8488-11e8-877d-0fd8203752b9.png)

The dimensions will be the accounting names you used.

To run netdata as root under systemd, you need to edit `/etc/systemd/system/netdata.service` and `/etc/netdata/netdata.conf` to set `[global].run as user = root` and also uncomment the `[web].web files owner = netdata` and `[web].web files group = netdata` (so the web files will remain owned by netdata).

**Comment by ktsaou** [comment]
oh, I forgot.
You need to compile netdata with NFACCT too. To do this, reinstall netdata and append to the installer the option `--enable-plugin-nfacct`.

**Comment by sereeds** [comment]
OK this is feature is really cool.  
Can I do accounting on any matched traffic, not just blacklist ?  
Is there any limits to how many?

**Comment by ktsaou** [comment]
Just append `accounting NAME` to any firehol command. Use as many as you like...

You can also see the counters like this:

```sh
# nfacct list
{ pkts = 00000000000000000546, bytes = 00000000000000070235 } = work;
{ pkts = 00000000000006859486, bytes = 00000000000559791691 } = deluge;
{ pkts = 00000000000105331109, bytes = 00000000041419851861 } = test;
```

**Comment by ktsaou** [comment]
and keep in mind multiple firehol statements can share the same accounting name (so all these rules will update the same counters).

**Comment by sereeds** [comment]
I'm having some issues compiling it with nfacct, on CentOS 7.
When I run:
`netdata-installer.sh --enable-plugin-nfacct`

I get some errors about netfilter accounting not found.  I searched for all the CentOS packages related netfilter, and installed them all, but still can't build it.

```
checking for NFACCT... no
checking for LIBMNL... yes
configure: error: netfilter_acct required but not found
 FAILED
```
I am guessing there is something missing from my OS, or something I have to enable?

**Comment by sereeds** [comment]
OK, so I can build Netdata on CentOS with netfilter accounting.
I am having problems with firehol and the accounting.

I get this warning when I run a "firehol start":
`Accounting is requested, but accounting is disabled. Is nfacct installed?`

However on that same system, I can run these commands:
nfacct add http-ipv4
iptables -I OUTPUT -p tcp --dport 80 -m nfacct --nfacct-name http-ipv4
nfacct list

`{ pkts = 00000000000000000006, bytes = 00000000000000000401 } = http-ipv4;`

So it appears that netfilter accounting is working, it's counting traffic, and even shows a graph in netdata for it.

But firehol doesn't like me adding "accounting test1" to my config.
So I'm half way there.  It seems to be working, but of course I want to use firehol.conf to specify my accounting, not iptables commands.  Not sure why firehol doesn't see it.

**Comment by ktsaou** [comment]
hm... could you please re-install firehol? This is a build time decision and it seems you installed `nfacct` after installing firehol.

**Comment by ktsaou** [comment]
Alternatively, you can also try setting this at the top of firehol.conf:

```sh
NFACCT_CMD="$(which nfacct)"
```

**Comment by sereeds** [comment]
OK I got it working, thanks.

I was using the firehol RPM package, and not building from source.
So after building and installing firehol on that machine, it works great.
Like you mentioned, it's a build time decision for the nfacct.

Thank you.

**Comment by sereeds** [comment]
On this subject, could you please provide a couple example accounting config lines for firehol.
I see I can add "accounting name" to any config lines.

I want to match some traffic to accounting, but I don't actually want to "do" anything with the traffic.
Is there a passive command to add some matches to accounting?

I know that firehol blocks all the remaining traffic not matched.  How would I match some packets to accounting, that are dropped by default.  Let's say I want to use accounting for all the incoming packets to port 22 that were dropped. 
Maybe that's related to my first question.  Config to use accounting, but not interfere with what firehol was doing with that traffic.

I assume it works with ipsets too right?

**Comment by ktsaou** [comment]
> know that firehol blocks all the remaining traffic not matched. How would I match some packets to accounting, that are dropped by default. Let's say I want to use accounting for all the incoming packets to port 22 that were dropped.

You have many options:

1. add a `server` or `client` statement to drop it, and append `accounting NAME` to it

2. add iptables commands directly in firehol.conf (use just `iptables ...`, not `/sbin/iptables ...` - ie without the path - the iptables command within `firehol.conf` is a wrapper to the real command).

3. To use firehol syntax for the matches, use the `rule` command like this:

```
rule chain CHAIN_NAME table TABLE_NAME <firehol optional rule parameters> action NONE
```

For example, to see what this does:

```sh
# firehol explain

FireHOL 3.1.6_master
(C) Copyright 2003-2015 Costa Tsaousis <costa@tsaousis.gr>
(C) Copyright 2012-2015 Phil Whineray <phil@firehol.org>
FireHOL is distributed under the GPL v2+.
Home Page: http://firehol.org

-------------------------------------------------------------------------
Get notified of new FireHOL releases by subscribing to the mailing list:
    http://lists.firehol.org/mailman/listinfo/firehol-support/
-------------------------------------------------------------------------

You can now start typing firehol configuration directives.
Special interactive commands: help, show, quit

# FireHOL [:] > rule chain INPUT table filter accounting test action NONE
# \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
# Cmd Line : 1@Interactive User Input
# Command  : rule chain INPUT table filter accounting test action NONE
/sbin/iptables -t filter -A INPUT -m nfacct --nfacct-name test
/sbin/ip6tables -t filter -A INPUT -m nfacct --nfacct-name test

# > OK <
```



> I assume it works with ipsets too right?

yes, it works.

**Comment by ktsaou** [comment]
btw, you can also use:

```
interface ...
   server ssh none accounting test
```

`none` is an action, much like `accept`, `reject`, etc. that does nothing.

**Comment by sereeds** [comment]
Thank you, almost all those methods worked good for me.

There is only 1 that didn't work.  
I can't append "accounting NAME" to any blacklist commands.
I get the following error:
```
ERROR   : # 1.
WHAT    : A runtime command failed to execute (returned error 1).
SOURCE  : 11@/etc/firehol/firehol.conf: blacklist4:
COMMAND : /usr/sbin/iptables -t filter -A BLACKLIST.uni.1.in -m nfacct --nfacct-name black
OUTPUT  :

iptables: No chain/target/match by that name.

 FAILED
```
Of course I was able to add accounting to the ipset, by moving it to another line and used a match with "none" action.  It works good.  Not sure why the blacklist4 command doesn't like accounting.
Thanks again for your help.

**Comment by ktsaou** [comment]
Can you post the `blacklist` statement that failed?

**Comment by sereeds** [comment]
I can no longer reproduce the error.  I think the issue was with my ipset.  
It may have been blank, not sure.
I have since updated ipsets, and everything works good now.  I can even add accounting to blacklist now.

Sorry about that.

**Comment by ktsaou** [comment]
ok, no problem...
