### ISSUE TITLE
No traffic is classified, not even as default - HELP

### ISSUE THREAD

**Issue by instantepiphany** [firehol/firehol#362]
I have simplified my config as much as is possible - `enp4s0` is the interface for my modem router.
When I run `fireqos status world-in` (or with `world-out`) I get no classified packets in the voip class or the default class, see picture below.

I am probably doing something super simple wrong, but I can't figure out what. Netstat doesn't show its QOS statistics at all.

```
DEVICE="enp4s0"
    INPUT_SPEED="110000kbit"
    OUTPUT_SPEED="90000kbit"
    LINKTYPE="adsl local pppoe-llc"
    interface $DEVICE world-in input rate $INPUT_SPEED $LINKTYPE # removed balanced
    interface $DEVICE world-out output rate $OUTPUT_SPEED $LINKTYPE # removed balanced

```

![selection_024](https://user-images.githubusercontent.com/5311587/45288014-05c8c680-b52d-11e8-92a0-073923e7dbe1.png)

**Comment by kravietz** [comment]
I have noticed the same on Ubuntu 18, possibly change in `tc` options that broke FireHOL?

**Comment by instantepiphany** [comment]
Thanks for reporting also @kravietz!

**Comment by kravietz** [comment]
@instantepiphany can you possibly try to run it as `bash -x /usr/sbin/fireqos status world-in` and attach the output here?

**Comment by instantepiphany** [comment]
@kravietz sure, I will do that later and let you know.
I did figure out that it actually applies the correct `tc` commands - I gave one client 100% of the bandwidth and once I started a download on that client everything else slowed to a crawl. I also setup some more classes to safeguard interactive traffic and everything worked, there was a massive difference in loss of interactivity compared to not having fireqos running. So I think it is just the command fireqos is using to gather the class traffic information for the `status` command that needs patching.

If I get time I will find the code that handles that and try and figure it out. It could have been something changed in `iproute2` that fireqos needs to catch up with.

**Comment by kravietz** [comment]
The issue seems to be that fireqos script is unable to parse output from tc. When running `bash -x /usr/sbin/fireqos status world-in` this is displayed repeatedly:

```
TCBACKLOG_htb_1_17=$((0));
TCSTATS_htb_1_16=$(( (Sent*8) - OLD_TCSTATS_htb_1_16));
OLD_TCSTATS_htb_1_16=$((Sent*8));
TCDROPS_htb_1_16=$(( (dropped) - OLD_TCDROPS_htb_1_16));
OLD_TCDROPS_htb_1_16=$((dropped));
TCOVERS_htb_1_16=$(( (overlimits) - OLD_TCOVERS_htb_1_16));
OLD_TCOVERS_htb_1_16=$((overlimits));
TCREQUEUES_htb_1_16=$(( (requeues) - OLD_TCREQUEUES_htb_1_16));
OLD_TCREQUEUES_htb_1_16=$((requeues));
TCBACKLOG_htb_1_16=$((0));
TCSTATS_htb_1_19=$(( (Sent*8) - OLD_TCSTATS_htb_1_19));
OLD_TCSTATS_htb_1_19=$((Sent*8));
TCDROPS_htb_1_19=$(( (dropped) - OLD_TCDROPS_htb_1_19));
OLD_TCDROPS_htb_1_19=$((dropped));
TCOVERS_htb_1_19=$(( (overlimits) - OLD_TCOVERS_htb_1_19));
OLD_TCOVERS_htb_1_19=$((overlimits));
TCREQUEUES_htb_1_19=$(( (requeues) - OLD_TCREQUEUES_htb_1_19));
OLD_TCREQUEUES_htb_1_19=$((requeues));
TCBACKLOG_htb_1_19=$((0));
TCSTATS_htb_1_8000=$(( (Sent*8) - OLD_TCSTATS_htb_1_8000));
OLD_TCSTATS_htb_1_8000=$((Sent*8));
TCDROPS_htb_1_8000=$(( (dropped) - OLD_TCDROPS_htb_1_8000));
OLD_TCDROPS_htb_1_8000=$((dropped));
TCOVERS_htb_1_8000=$(( (overlimits) - OLD_TCOVERS_htb_1_8000));
OLD_TCOVERS_htb_1_8000=$((overlimits));
TCREQUEUES_htb_1_8000=$(( (requeues) - OLD_TCREQUEUES_htb_1_8000));
OLD_TCREQUEUES_htb_1_8000=$((requeues));
TCBACKLOG_htb_1_8000=$((0));
# Cannot parse fq_codel class 15_2ed
# Cannot parse fq_codel class 17_ba
# Cannot parse fq_codel class 14_7
# Cannot parse fq_codel class 14_19d
# Cannot parse fq_codel class 16_354
# Cannot parse fq_codel class 18_a4
# Cannot parse fq_codel class 18_ba
# Cannot parse fq_codel class 18_1cc
# Cannot parse fq_codel class 18_24c
# Cannot parse fq_codel class 13_aa
# Cannot parse fq_codel class 13_b4
# Cannot parse fq_codel class 13_181
# Cannot parse fq_codel class 13_1f5
# Cannot parse fq_codel class 13_260
# Cannot parse fq_codel class 13_3e1
# Cannot parse fq_codel class 15_2ed
# Cannot parse fq_codel class 17_ba
# Cannot parse fq_codel class 14_7
# Cannot parse fq_codel class 14_19d
# Cannot parse fq_codel class 16_354
# Cannot parse fq_codel class 18_a4
# Cannot parse fq_codel class 18_ba
# Cannot parse fq_codel class 18_1cc
# Cannot parse fq_codel class 18_24c
# Cannot parse fq_codel class 13_aa
# Cannot parse fq_codel class 13_b4
# Cannot parse fq_codel class 13_181
# Cannot parse fq_codel class 13_1f5
# Cannot parse fq_codel class 13_260
# Cannot parse fq_codel class 13_3e1'
```

**Comment by instantepiphany** [comment]
Thanks @kravietz - looks like that might help track down the issue.

**Comment by instantepiphany** [comment]
The code seems to be expecting a `htb` class:
```
{
	if( \$2 == "htb" ) {
		value = \$13;
		drops = \$18;
		overs = \$20;
		requeues = \$22;
		backlog = \$28;

		print "TCSTATS_" \$2 "_" \$3 "=\$(( (" value "*8) - OLD_TCSTATS_" \$2 "_" \$3 "));"
		print "OLD_TCSTATS_" \$2 "_" \$3 "=\$((" value "*8));"

		print "TCDROPS_" \$2 "_" \$3 "=\$(( (" drops ") - OLD_TCDROPS_" \$2 "_" \$3 "));"
		print "OLD_TCDROPS_" \$2 "_" \$3 "=\$((" drops "));"

		print "TCOVERS_" \$2 "_" \$3 "=\$(( (" overs ") - OLD_TCOVERS_" \$2 "_" \$3 "));"
		print "OLD_TCOVERS_" \$2 "_" \$3 "=\$((" overs "));"

		print "TCREQUEUES_" \$2 "_" \$3 "=\$(( (" requeues ") - OLD_TCREQUEUES_" \$2 "_" \$3 "));"
		print "OLD_TCREQUEUES_" \$2 "_" \$3 "=\$((" requeues "));"

		print "TCBACKLOG_" \$2 "_" \$3 "=\$((" backlog "));"
	}
	else {
		print "# Cannot parse " \$2 " class " \$3;
		value = 0;
	}
}
```

**Comment by instantepiphany** [comment]
Changing my configs classes to use sfq results in the same error but fq_codel is swapped out for sfq. I think fireqos is supposed to change the classes to htb at somepoint, otherwise I don't understand why this conditional is expecting htb.

**Comment by instantepiphany** [comment]
@philwhineray @ktsaou is this enough info to help narrow down the cause?

**Comment by benadler** [comment]
I have the same problem on ubuntu 18.04:
![fireqos](https://user-images.githubusercontent.com/99470/47613361-beb77600-da85-11e8-8502-54a7d41cb9ac.png)

**Comment by mitchcapper** [comment]
this was fixed for me using 3.16 which is not stable on ubuntu yet but compiling from source it works.

**Comment by jimsalterjrs** [comment]
I can confirm that this is an issue with 3.1.5 (which is in the default Ubuntu Xenial and Bionic repos) but not with 3.1.6 (which is in the Debian Buster repos). 

I can also confirm that downloading .debs from Debian Buster and manually installing with `dpkg -i` works on Ubuntu 18.04.

**Comment by instantepiphany** [comment]
Confirmed also, upgrading my server to use `3.1.6` has resolved the issue, and traffic is classified as default.

I happen to use nixos, and for other nixos users, nixos 18.09 contains firehol/qos 3.1.6 so once you upgrade to 18.09 restart the fireqos service and then run `fireqos status (interface name)` to see traffic classified correctly.

**Comment by instantepiphany** [comment]
Thanks everyone for the help!
