### ISSUE TITLE
how to edit the doc ?

### ISSUE THREAD

**Issue by jodumont** [firehol/firehol#366]
I was looking to change/edit/PR this page (https://firehol.org/faq/#switch-to-nflog)
but i'm unable to find it

so to be in the mood of reconfiguration/overlaps'ish via 
/etc/firehol/firehol.conf instead of editing the core config

I tried with success to put
`FIREHOL_LOG_MODE="NFLOG"` in `/etc/firehol/firehol.conf`

#### So I would like to propose/change this part

`If you then set FIREHOL_LOG_MODE="NFLOG" in /etc/firehol/firehol-defaults.conf then FireHOL will use NFLOG with iptables, rather than the output going to normal syslog. 
`
##### FOR

`If you then set FIREHOL_LOG_MODE="NFLOG" in /etc/firehol/firehol.conf then FireHOL will use NFLOG with iptables, rather than the output going to normal syslog. `

**Comment by philwhineray** [comment]
Well, the website repo is this: https://github.com/firehol/website

The FAQs are each in a file and the one you are referring to is in `content/faqs/0002-0007-logging.md`.

Adding the value to `firehol.conf` is supported, but if you are submitting a change I'd sooner not lose the reference to `firehol-defaults.conf` altogether.

I think the main purpose of `firehol-defaults.conf` is not that you don't edit it, so much as it is to get config variables, some of which are shared with tools like fireqos, out of the main `firehol.conf` file.
