### ISSUE TITLE
Need better way to nat http/https without wan ip  -  also would like a proper forum.

### ISSUE THREAD

**Issue by dkebler** [firehol/firehol#370]
Running latest firehol from the repo.   @philwhineray Just want to nat my wan interface ports 80 and 443 to an internal server.   Never found a good example of something basic until I came across another issue here. #357 which gave me some ideas.

What I got to work needs the wan IP.   I would like this to work without relying on the wan ip `174.224.282.133` as that will change from time to time and totally break my firewall until I fix it. 
My question/issue: Is there a better way than below and one that doesn't require using the wan ip? 

```
version 6

# the device that connects you to the internet
world="wan"

# the device that connects you to your home PCs
home="br0"

# have outgoing traffic use the public IP
  ipv4 masquerade "${world}"


# nat http and https to internal server
dnat4 to 10.0.0.3   inface ${world} proto tcp  dport 80,443    # http,https to NAS Caddy Server
snat4 to 174.224.282.133 outface ${world} src 10.0.0.0/24
router4 internet2lan inface ${world} outface ${home} dst 10.0.0.0/24
        client all             accept
        server http,https      accept dst 10.0.0.3

# LAN network facing interface
interface "${home}" home
   policy accept


# internet facing wan interface
interface "${world}" world
   protection bad-packets
   server ssh accept
   server icmp accept
   client all accept
```

And please can @philwhineray can you consider running a proper forum https://github.com/discourse/discourse or at least make a tag for server fault https://serverfault.com/.  Asking questions in this issue tracker is the only way I've found traction :-(.

**Comment by philwhineray** [comment]
Did you try just removing the `snat` command? I don't believe it should be needed in addition to masquerade, but perhaps there is a bug in the generated rules:

https://firehol.org/guides/firehol-welcome/#source-nat

**Comment by dkebler** [comment]
taking out the snat worked.    

Would have really nice if the tutorial had a simple clear example of how to nat a wan interface (some port) to a lan ip (some port).    This is a typical thing to add to any gateway router firewall especially if there lan has a web server serving stuff out on the internet.
