### ISSUE TITLE
transparent_squid looks different than traditional dnat rules

### ISSUE THREAD

**Issue by bunder2015** [firehol/firehol#385]
thought i would give firehol a go, but i am seeing some syntax differences that i'm not quite sure of...  perhaps my understanding of iptables/netfilter is incorrect...  anywho, my current hand-written iptables script does transparent proxy similar to how `dnat` does it, eg:

```
dnat 192.168.0.1:squid inface eth1 proto tcp dport http
/sbin/iptables -t nat -A PREROUTING -i eth1 -p tcp --dport http -m conntrack --ctstate NEW -j DNAT --to-destination 192.168.0.1:squid
```

however the documentation suggests i should use transparent_squid instead, and that gives me:

```
ipv4 transparent_squid squid "" inface eth1
/sbin/iptables -t nat -A PREROUTING -i eth1 -p tcp --sport 1024:65535 --dport 80 -j REDIRECT --to-ports squid
```

does changing DNAT for REDIRECT affect any functionality?  also, what about the lack of ctstate NEW when using transparent_squid?

thanks for the insights

**Comment by philwhineray** [comment]
There is no real difference from an iptables point of view:

    https://netfilter.org/documentation/HOWTO/NAT-HOWTO-6.html#ss6.2

The lack of connection tracking won't make much difference in practice, I suspect.

**Comment by bunder2015** [comment]
interesting.  thanks for the link...
