### ISSUE TITLE
unzip not installed ?

### ISSUE THREAD

**Issue by imTHAI** [firehol/firehol#400]
Hello,
When I run update-ipset after enabling geo ip localisations list, I get errors:
```
                  geolite2_country|  ERROR  Command 'unzip' is not installed.
                                   |
                       geolite2_asn|  ERROR  Command 'unzip' is not installed.
                                   |
                     ipdeny_country|  DISABLED
                                   | To enable run: update-ipsets enable ipdeny_country
                                   |
                ip2location_country|  ERROR  Command 'unzip' is not installed.
                                   |
                       ipip_country|  ERROR  Command 'unzip' is not installed.
```

But unzip is installed ! I'm under Archlinux.
Can you help me ?
Thank you

**Comment by philwhineray** [comment]
I'm not familiar with how the tool is packaged on Arch (if you installed Fire manually, unzip was not found at the time you ran configure).

The quickest way round this is probably to add: 

```
UNZIP_CMD=/usr/bin/unzip
```

To your `/etc/firehol/firehol-defaults.conf` file (replace the `/usr/bin` if necessary).

**Comment by imTHAI** [comment]
It worked perfectly ! Thank you
