### ISSUE TITLE
How to set an empty inface on blacklist

### ISSUE THREAD

**Issue by lfdominguez** [firehol/firehol#408]
Hi again. Well i have a firewall (gateway) with FireHOL blocking TOR with the update-ipsets

```
Server --> Firewall --> Internet
```

```
for x in firehol_anonymous
do
  ipset4 create  ${x} hash:net
  ipset4 addfile ${x} ipsets/${x}.netset
  blacklist4 full inface "ens32" log "${x^^}: " ipset:${x}
done
```

Now i need to execute a TOR client only on the firewall, but the blacklist dont letme. I was tested put `except src <firewall ens32 ip>` and dont work, then i was thinking put something like `except inface empty` but i dont know how.

**Comment by mikenor** [comment]
I've never worked with blacklists but according to the manual, `full` creates a bi-directional stateless blacklist. So your exemption will need to match both directions. I'm assuming you need something like `except src ${firewall_ip} or dst ${firewall_ip}`.

**Comment by lfdominguez** [comment]
ummm letme try...

**Comment by lfdominguez** [comment]
Fixed by @mikenor approach, thanks
