### ISSUE TITLE
Firehol try reset connections

### ISSUE THREAD

**Issue by nmarantos** [firehol/firehol#478]
Hi,

I need a help with an issue during firehol try. I am using Ubuntu 20.04 with firehol 3.1.7 under VM. I have also installed the conntrack on it.

When i am doing firehol try, firehol delete all established NATs and after that recreate them. From tcpdump i am seeing that during firehol try the connection is reset and a connection with a specific source port is changed.

Have you any idea or any solution about this issue?

**Comment by nmarantos** [comment]
During firehol try (not every time) some connections close and recreated with new source ports and after that destroy the older connections with the older source ports.

**Comment by fred0r** [comment]
thats correct - pls close this issue.
