### ISSUE TITLE
autoconf enable/with have no effect

### ISSUE THREAD

**Issue by alonbl** [firehol/firehol#71]
Hi,

As far as I can see there is an attempt to use autoconf to define default for these:
```
  --with-autosave[[[=PATH]]]
  --with-autosave6[[[=PATH]]]
```

However, I cannot see where it is used, in sbin/firehol there is:
```
# Where /etc/init.d/iptables expects its configuration?
# Leave it empty for automatic detection
test -z "$FIREHOL_AUTOSAVE" && \
        FIREHOL_AUTOSAVE=

# Where /etc/init.d/ip6tables expects its configuration?
# Leave it empty for automatic detection
test -z "$FIREHOL_AUTOSAVE6" && \
        FIREHOL_AUTOSAVE6=
```

I guess it should be  @FIREHOL_AUTOSAVE@ and  @FIREHOL_AUTOSAVE6@ as detection and setting performed by autoconf.

I am unsure what the intention was, I just do not see these been used anywhere and I do want package customization for users.

Thanks!

**Comment by philwhineray** [comment]
Hi

The autoconf stuff was added during the sanewall fork, which does honour those flags I think. The configure logic got merged back in, but not all the variables it can set.

Which branch are you interested in? In the master branch which will become 3.0 firehol will read /etc/firehol/firehol-defaults.conf for this sort of information. I guess it would make sense for the autoconf to create this file for distribution purposes (it does not currently) and would be the obvious place to set these flags.

If you are looking at 2.x then currently you can either force the environment variable before the script runs (e.g. in a debian /etc/defaults/firehol style file) if you have the necessary infrastructure or the firehol.in needs updaing as you suggest but with the caveat that the firehol.in is expected to work even without configure being run on it, so a bit of extra logic would be needed.

**Comment by alonbl** [comment]
Hi!

Thanks for the explanation.

For now I used the following patch[1].

Regards,
Alon Bar-Lev.

[1] https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-firewall/firehol/files/firehol-2.0.2-autosave.patch?revision=1.1&view=markup

**Comment by alonbl** [comment]
same for need programs, example:  IP6TABLES_RESTORE_CMD, IP6TABLES_SAVE_CMD

although autoconf detects these nothing actually use it.

this has the side effect that user who has no ipv6 cannot execute configure while the firehol script auto detect this at runtime.

not sure if you want to detect it at runtime or at build time, if at runtime please remove all these AC_CHECK_PROG, AX_NEED_PROG from configure.ac.

thanks!
