### ISSUE TITLE
Dynamic NAT Range of Ports

### ISSUE THREAD

**Issue by oneguynick** [firehol/firehol#72]
After pouring over the documentation I do not see where it is possible to dynamically NAT a range of ports. I was expecting to see something similar to:

ipv4 dnat to 192.168.1.1:5060:5075 proto tcp dport 5060:5075

Am I missing the configuration line item for this or is there another capability I should use?

**Comment by philwhineray** [comment]
iptables (and so firehol) requires that you speciy your "to" port range with a dash, presumably to distinguish it from the ip:port separator. This is what I think you need to write:

~~~~
ipv4 dnat to 192.168.1.1:5060-5075 proto tcp dport 5060:5075
~~~~

**Comment by oneguynick** [comment]
No that didn't work unfortunately:

firehol.conf
`ipv4 dnat to 10.0.1.150:5060-5075 proto tcp dport 5060-5075`

--------------------------------------------------------------------------------
ERROR   : # 1.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : line 21 of /etc/firehol/firehol.conf
COMMAND : /usr/bin/iptables -t nat -A PREROUTING -p tcp --dport 5060-5075 -j nat.7 
OUTPUT  : 

iptables v1.4.21: invalid port/service `5060-5075' specified
Try `iptables -h' or 'iptables --help' for more information.

 FAILED


FireHOL: Restoring old firewall: OK

Broadcast message from systemd-journald@sidewinder (Thu 2015-04-23 11:17:13 EDT):

FireHOL[19326]: FAILED to activate the firewall from /etc/firehol/firehol.conf. Last good firewall restoration: OK.

**Comment by philwhineray** [comment]
The `dport` still needs a colon, e.g. `5060:5075` which is ugly but should work, at least it did on my more recent iptables, v

**Comment by oneguynick** [comment]
Basically the same error. Iptables cannot parse dport:5060-5075

**Comment by oneguynick** [comment]
Any ideas?

**Comment by philwhineray** [comment]
Sorry, for some reason github did not notify me of your last update.

I think you have introduced another error.

Look closely at my example. I suggest copy and paste it, check it works and
then update the ip address.

Hope that helps.
