### ISSUE TITLE
GitHub organisation

### ISSUE THREAD

**Issue by philwhineray** [firehol/firehol#81]
We should transfer the various repositories (ktsaou/firehol, philwhineray/firehol-infrastructure,  philwhineray/firehol-website) into a firehol organisation. This will allow us to better manage the project long-term.

https://github.com/blog/674-introducing-organizations
https://help.github.com/articles/transferring-a-repository/

I note that someone has set up a firehol organisation - it is you @ktsaou and if so can you add me to it? If not, definitely don't transfer anything into it since I have no control over it either.

**Comment by ktsaou** [comment]
https://github.com/firehol

I don't know who created... It seems orphan...

**Comment by philwhineray** [comment]
I have sent a request into github support to see if they can help work out who created it and if it can be reassigned.
