### ISSUE TITLE
Install iprange program

### ISSUE THREAD

**Issue by philwhineray** [firehol/firehol#85]
Installing with ./configure && make && make install should build and install iprange.

**Comment by philwhineray** [comment]
Latest master will build and install `iprange` to `/sbin`.

It can be disabled with `--disable-iprange`.

**Comment by ktsaou** [comment]
@philwhineray I see it is compiled with `-g -O2`.

This will have a huge impact on performance (`-g` is instructing gcc to produce a debugger friendly executable).

I suggest to compile just with `-O3`.

**Comment by philwhineray** [comment]
We are not really supposed to do this:

http://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html#C-Compiler
http://stackoverflow.com/questions/6311570/autoconf-automake-versus-o2-versus-o3

Running configure with the flags you want will work:

~~~~
CFLAGS=-O3 ./configure
~~~~

I will add a suggestion to the README.

**Comment by ktsaou** [comment]
ok. I didn't know all these...
