### ISSUE TITLE
addfile feature does not resolve names

### ISSUE THREAD

**Issue by grpomega** [firehol/firehol#98]
ipset addfile does not resolve names and only allows ip addresses.
this seems to be by design, the filters in the addfile function eliminates all characters except for digits and '.'
My first guess as to the objective of the filter is to remove comments.

This feature would have greater applicability if you were to allow ip names, the standard ipset command allows this, as does your aliased "ipvX ipset" command

I didn't take time to determine what it would take to change the existing command but a naive solution follows.

##############################################
ipset_create(){
 setname="$1"
 type="$2"
 exists=`/bin/ipset list "$setname" | grep -i type| awk '{print $2}'`
 if [ -z "$exists" ]
  then
  /bin/ipset create $setname $type
  fi
}
##############################################
ipset_addfile_resolve(){
 setname="$1"
 file="$2"
 if [ ! -e "$file" ]
  then
  echo "No file: $file"
  return
  fi
 settype=`/bin/ipset list "$setname" | grep -i type| awk '{print $2}'`
 if [ -z "$settype" ]
  then
  echo "No set: $setname-type=$settype"
  return
  fi

 setTMP="$setname""TMP"
 /bin/ipset create "$setTMP" "$settype"
 cat "$file" | while read line
  do
  line=`echo "$line" | cut -f 1 -d#`
  /bin/ipset add "$setTMP" $line 
  done 
 /bin/ipset swap "$setname" "$setTMP"
 /bin/ipset destroy "$setTMP"
}

**Comment by ktsaou** [comment]
Well, I didn't know this.

However there are a few issues with it:

1. FireHOL passes all ipset files through iprange to eliminate the duplicates and reduce their subnets (hash:net) for optimal kernel performance. iprange does not support host resolution.

2. Older versions of ipset and kernels do not support the ipset option ` -! ` which ignores duplicates. This means that ipsets which happen to resolve to the same IP will fail to be loaded. Also, in older kernels you cannot mix IPs and subnets on the same ipset (even for hash:net ipsets). If we don't grep either out, they will fail.

3. FireHOL is designed in such a way that it should be able to be activated before any network interface is active (or when the panic mode is active which drops all connections on all interfaces). This actually means that if you use names, the firewall may fail to be activated at certain cases.

So, in general, your proposal is handy, but problematic.
I am not sure how we can support this...

**Comment by grpomega** [comment]
Yes,
First, Great work on firehol!!

agreed, the design objective of firewall before network activation sort of kills this.

Maybe a separate resolution process running and waiting for the network to come up.  Would that sort of thing fit into your design criteria?

ipset_addfile_resolve()
.
.
.

cat "$file" | while read line
do
line=echo "$line" | cut -f 1 -d#
numericLine=`echo "$line" | tr -d [:alpha:]`
if [ "$line" != "$numericLine" ]
 then
 BackgroundResolve setname type line
 fi
/bin/ipset add "$setTMP" $line
done 
.
.
.

BackgroundResolve.sh
#!/bin/bash

append parameters to BackgroundResloveFile and end
test for BackgroundResolveSemaphore
if BackgroundResolveSemaphore already running exit

>BackgroundResolveSemaphore
while network down
sleep

cat BackgroundResolveFile | while read line
 resolve line
 parse line
 test for line content in existing set
 ipseet add  line contents

rm BackgroundResovleSemaphore BackgroundResolveFIle

**Comment by grpomega** [comment]
should have read:
BackgroundResolve


#!/bin/bash

append parameters to BackgroundResloveFile and end
test for BackgroundResolveSemaphore
if BackgroundResolveSemaphore already running exit

set BackgroundResolveSemaphore
while network down
sleep

cat BackgroundResolveFile | while read line
 resolve line
 parse line
 test for line content in existing set
 ipseet add  line contents

rm BackgroundResovleSemaphore BackgroundResolveFIle

**Comment by grpomega** [comment]
and the loop in ipset_addfile_resolve should continue after the call to BackgroundResolve

**Comment by ktsaou** [comment]
The github version of `iprange` included in firehol, resolves hostnames (it is very efficient - it can do parallel async DNS queries).

However, I will not support this directly in firehol, since the firewall will fail to be restored at next boot (the firewall is activated before any network is active).

I suggest to use hostnames like this:

1. Assuming you have a file named `hosts` with hostnames (and possibly IPs, subnets, etc)
2. Run `iprange hosts >hosts.ipset`. This will resolve all names to IPs, normalize the file, etc.
3. In `firehol.conf` use `hosts.ipset` with `addfile`.

So, every time you update the `hosts` file, run `iprange hosts >hosts.ipset` and then `firehol start` or `firehol try`.

This procedure will ensure that the firewall can be applied in all cases.

**Comment by ktsaou** [comment]
Just note that `iprange hosts >hosts.ipset` may produce subnets in the output file.
To force `iprange` always output single ips, use:

```sh
iprange -1 hosts >hosts.ipset
```

The parameter `-1` forces `iprange` to write single IPs instead of subnets.

**Comment by grpomega** [comment]
Ok,
Thank you for the input
